import { readFileSync, mkdirSync, writeFileSync, copyFileSync } from 'node:fs';
import { resolve, join } from 'node:path';

const chapterDir = resolve('../.corpus-orthopedie/techniques-de-reconstruction-cartilagineuse');
const draftDir = join(chapterDir, 'delivery', 'draft-2026-08-10');
const out = join(chapterDir, 'delivery', 'published-2026-08-10');
mkdirSync(out, { recursive: true });

// Chaque carte est une notion autonome retrouvée dans extract.json (blocs
// 9-184). Les questions et les DP plus bas sont rédigés séparément : aucune
// option n'est dérivée mécaniquement des cartes.
const facts = [
['Quelle lésion cartilagineuse focale peut relever d’une chirurgie ?','Une lésion profonde, symptomatique, isolée et située en zone portante.'],
['Quelles sont les causes habituelles des lésions chondrales focales ?','Un traumatisme ou une ostéochondrite.'],
['Pourquoi le cartilage articulaire se répare-t-il peu spontanément ?','Il est avasculaire et aneural ; ses cellules sont nourries par diffusion dans la matrice.'],
['Quelles fonctions mécaniques assure le cartilage articulaire ?','Transmission et absorption des contraintes, faible friction et résistance à l’usure.'],
['Quel tissu cherche-t-on idéalement à restaurer ?','Un cartilage hyalin, sur un support osseux adapté.'],
['Quelle réparation obtient surtout une stimulation sous-chondrale ?','Un fibrocartilage de réparation, biomécaniquement moins performant.'],
['Quel est l’objectif commun des gestes de reconstruction cartilagineuse ?','Restaurer la congruence et limiter la dégénérescence arthrosique.'],
['Quelle est la première étape de la stratégie thérapeutique ?','Un bilan fonctionnel, clinique et morphologique de la lésion.'],
['Que mesure le bilan fonctionnel préopératoire ?','La douleur, les mobilités et les limitations dans les activités pertinentes.'],
['Pourquoi utiliser une évaluation fonctionnelle chiffrée ?','Pour quantifier le handicap initial puis comparer le résultat postopératoire.'],
['Quelles activités interrogent particulièrement le membre inférieur ?','La marche et la montée ou descente des escaliers.'],
['Quels paramètres de terrain doivent être recherchés ?','Poids, activités actuelles et souhaitées, morphotype, stabilité et âge.'],
['Pourquoi rechercher un défaut d’axe ?','Il modifie les contraintes locales et peut compromettre une réparation cartilagineuse.'],
['Pourquoi rechercher une laxité articulaire ?','La laxité est un facteur de dégradation cartilagineuse et doit être prise en compte.'],
['Quel effet a l’âge avancé sur la réparation ?','Les résultats diminuent avec la raréfaction des cellules souches sous-chondrales.'],
['Quelle situation arthrosique exclut une réparation locale ?','Des lésions en miroir d’arthrose ou une arthrose avérée.'],
['Quels éléments radiologiques évaluent la lésion ?','Sa taille, sa topographie et l’état de l’os sous-chondral.'],
['Que détectent surtout les radiographies standard au genou ?','Une atteinte de l’os sous-chondral et une estimation de la lésion.'],
['Quels examens cartographient finement une lésion chondrale du genou ?','Arthroscanner, IRM et arthro-IRM.'],
['Quel inconvénient limite l’arthroscanner répété ?','Son caractère invasif et l’irradiation.'],
['Quelles séquences IRM simples sont citées pour le cartilage ?','FSE T2 et 3D GRE T1.'],
['Quels clichés initiaux sont demandés pour une cheville ?','Face en rotation interne (mortaise) en charge et profil en charge.'],
['Quels signes sont recherchés sur les radiographies de cheville ?','Lésion du dôme talien, corps libres, ostéophytes et pincement de l’interligne.'],
['Quel intérêt de l’IRM à la cheville ?','Détecter notamment les lésions de bas grade et l’œdème médullaire.'],
['Quel intérêt de la scintigraphie en cas de doute ?','Dépister ou confirmer une lésion ostéochondrale avant d’autres imageries.'],
['Quel est le principe du lavage-débridement ?','Laver l’articulation et retirer les tissus détériorés.'],
['Qu’élimine le lavage articulaire ?','Des cytokines, métalloprotéases, produits de dégradation, débris et cristaux irritants.'],
['Quelle est la durée habituelle de l’effet du lavage ?','Symptomatique et transitoire, de quelques mois à environ un an.'],
['Quand le lavage apporte-t-il peu de bénéfice ?','En cas de disparition complète du cartilage avec contact os contre os.'],
['Quel est le principe des stimulations ostéochondrales ?','Exposer l’os sous-chondral pour former un caillot colonisé par des cellules mésenchymateuses.'],
['Quelle est la nature du tissu obtenu après microfractures ?','Un tissu majoritairement fibrocartilagineux, différent du cartilage hyalin.'],
['Quel est le rôle du caillot fibrinocruorique ?','Supporter cellules mésenchymateuses, plaquettes et facteurs de croissance.'],
['Pourquoi la microfracture utilise-t-elle un poinçon ?','Pour éviter un dommage thermique de l’os sous-chondral.'],
['Quel est le délai de formation du fibrocartilage après microfractures ?','Environ six à huit semaines.'],
['Pour quel profil la source réserve-t-elle les microfractures ?','Un patient ayant une faible demande fonctionnelle.'],
['Quel est le principe de la perforation de Pridie ?','Créer des perforations de l’os sous-chondral pour communiquer avec l’os spongieux.'],
['Que favorisent les canaux de Pridie ?','Migration cellulaire, néovascularisation et décompression de l’os sous-chondral.'],
['Quel instrument historique est associé à Pridie ?','Une broche de Kirschner.'],
['Quel est le principe de l’abrasion arthroplastique ?','Créer des sillons superficiels de l’os sous-chondral au moyen d’une fraise.'],
['Quel risque fait abandonner la greffe de périoste isolée ?','La calcification ou l’ossification tardive du périoste.'],
['Où prélève-t-on classiquement le périoste ?','À la partie proximale du tibia, vers la patte d’oie.'],
['Quelle orientation du périoste est décrite sur la lésion ?','Face superficielle vers le receveur.'],
['Quelle mesure postopératoire est indispensable après greffe de périoste ?','Une mobilisation passive.'],
['Quel est le principe de l’allogreffe ostéochondrale ?','Implanter un fragment ostéochondral sur un sous-sol osseux saignant préparé.'],
['Quelle forme d’allogreffe préserve mieux les chondrocytes ?','L’allogreffe fraîche, mieux que la congélation.'],
['Quelle contrainte organisationnelle limite les allogreffes ?','Le besoin d’une banque tissulaire et de prélèvement/implantation rapides.'],
['À quel type de perte de substance l’allogreffe est-elle destinée ?','Une perte de substance ostéochondrale volumineuse.'],
['Qu’est-ce que le press-fit en mosaïcoplastie ?','La stabilité du plot impacté par effet de coin sans fixation externe habituelle.'],
['Quand peut-on ajouter un vissage à une mosaïcoplastie ?','Si une stabilisation complémentaire du greffon est nécessaire.'],
['Quelle anomalie doit être corrigée si elle existe avant mosaïcoplastie ?','Un défaut d’axe frontal, par ostéotomie tibiale ou fémorale adaptée.'],
['Quelle règle de rééducation suit la mosaïcoplastie ?','Mobilisation/rodage précoce sans appui, puis reprise progressive.'],
['Quel est le principe de l’autogreffe ostéocartilagineuse pâteuse ?','Combler le defect avec un mélange d’os spongieux autologue et de tissu ostéochondral morcelé.'],
['Quelle étape précède ce comblement pâteux ?','Shaving du cartilage instable puis microfractures jusqu’au saignement.'],
['Quel site peut fournir le greffon cylindrique autologue ?','L’échancrure intercondylienne.'],
['Pourquoi l’arthroscopie aide-t-elle la mosaïcoplastie ?','Elle améliore le contrôle du remplissage, de la congruence et des hauteurs cartilagineuses.'],
['Quelle durée de décharge est décrite après greffe ostéochondrale ?','Environ quatre à huit semaines selon taille et localisation.'],
['Pourquoi l’abord de la cheville peut-il être ouvert ?','Pour introduire les greffons perpendiculairement à la lésion.'],
['Quand une ostéotomie malléolaire latérale est-elle nécessaire ?','Pour les lésions postérolatérales ou supérieures du dôme talien peu exposables.'],
['Quelle technique cellulaire est la première génération ?','La culture de chondrocytes autologues sous lambeau périosté.'],
['Quel est le principe de la culture de chondrocytes autologues ?','Prélever du cartilage sain, cultiver les chondrocytes puis les implanter dans la lésion.'],
['Quel site de prélèvement chondrocytaire est cité ?','Une zone non portante, notamment le bord médial du condyle fémoral fémoropatellaire.'],
['Quel est le délai de culture cellulaire de première génération ?','Environ trois semaines dans la source.'],
['Comment le patch périosté est-il étanchéifié ?','Par colle de fibrine après suture périphérique.'],
['Quelle orientation de la couche cambiale du périoste est requise ?','Vers l’os.'],
['Quelles contraintes suivent l’implantation de chondrocytes sous périoste ?','Absence d’appui et mobilisation passive pendant plusieurs semaines.'],
['Quand l’activité est-elle autorisée après première génération ?','Au-delà de six mois selon la source.'],
['Quelles complications sont liées au patch périosté ?','Ossification, arrachement, calcifications, fuites et hypertrophie.'],
['Pourquoi des matrices ont-elles remplacé le périoste ?','Pour éviter les problèmes spécifiques du patch périosté.'],
['Quels types de matrices de deuxième génération sont cités ?','Synthétiques, protéiques ou polysaccharidiques.'],
['Quel rôle de l’acide hyaluronique est cité ?','Participer à l’homéostasie matricielle et soutenir la chondrogenèse.'],
['Que doivent permettre les matrices de troisième génération ?','Conserver le phénotype, favoriser prolifération et synthèse matricielle.'],
['Quelles propriétés doit avoir un scaffold tridimensionnel ?','Biocompatible, biodégradable, bioactif, perméable et facile à utiliser.'],
['Quelles sont les trois phases de la troisième génération ?','Bilan/prélèvement, culture sur matrice 3D, puis implantation.'],
['Quelle quantité de cartilage est prélevée pour Cartipatch selon la source ?','Environ 200 mg de cartilage sain.'],
['Quel objectif de surface vise une matrice 3D implantée ?','Une surface harmonieuse sans marche d’escalier ni rupture de continuité.'],
['Quel protocole d’appui suit l’implantation d’une matrice 3D ?','Mobilisation passive sans appui un mois, puis reprise progressive.'],
['Quelle articulation est la principale étudiée pour ces techniques ?','Le genou.'],
['Quelle prudence faut-il avoir avec les résultats du lavage au genou ?','Ne pas en attendre de résultat spectaculaire durable.'],
['Quel facteur explique l’absence de preuve forte pour certaines techniques ?','Une littérature surtout rétrospective ou d’avis d’experts.'],
['Quelle technique est décrite comme référence en France ?','La mosaïcoplastie, technique délicate à maîtriser.'],
['Quelle taille lésionnelle est associée à la mosaïcoplastie dans l’algorithme du genou ?','Les petites lésions ; l’algorithme source situe le seuil autour de 2 cm².'],
['Quelle stratégie est évoquée entre 2 et 4 cm² au genou ?','Les greffes de chondrocytes de troisième génération peuvent trouver une place.'],
['Quelle stratégie est évoquée au-delà de 4 cm² au genou ?','Allogreffe/méga-OATS ou greffe de chondrocytes selon les possibilités.'],
['Quel préalable s’impose avant réparation d’une laxité associée ?','Reconstruire d’abord les ligaments.'],
['Quel seuil de déviation axiale est cité avant geste cartilagineux ?','Une réaxation est envisagée au-delà de 5 degrés.'],
['Quelle période d’observation est recommandée avant une réparation après correction associée ?','Trois à six mois.'],
['Quelle caractéristique définit une lésion candidate selon la conclusion ?','Une lésion unique, profonde, symptomatique, isolée et en zone portante.'],
['Quelles contre-indications majeures sont rappelées ?','Arthrose, obésité morbide, défaut d’axe et laxité non corrigés.'],
['Pourquoi l’adhésion du patient compte-t-elle ?','Âge, activité, motivation et capacité à suivre le protocole guident l’indication.'],
['Quelle attitude devant les techniques émergentes ?','Rester prudent et respecter les indications validées.'],
['Quelle place a le traitement conservateur d’une lésion talienne ?','Il doit être tenté en première intention dans la stratégie citée.'],
['Que montre la source sur le délai d’un an avant chirurgie de cheville ?','Le différer un an après traitement conservateur n’aggrave pas nécessairement l’évolution.'],
['Quand une perforation rétrograde est-elle indiquée au talus ?','Si le cartilage de surface est intact.'],
['Que peut associer une perforation rétrograde devant un kyste sous-chondral important ?','Une greffe osseuse.'],
['Quand la mosaïcoplastie est-elle indiquée à la cheville selon la source ?','Lésion plus importante atteignant l’os sous-chondral ou échec d’une technique traditionnelle.'],
['Pourquoi les lésions taliennes très étendues posent-elles problème ?','Elles ne sont plus facilement qualifiables de lésions focales et relèvent d’une réflexion arthrosique.'],
['Pourquoi limiter les indications aux autres articulations ?','Les séries sont courtes et ne permettent pas de recommandations généralisables.'],
['Quels éléments articulaires associés doivent être évalués ?','État ligamentaire, méniscal et morphotype global.'],
['Quel lien doit être vérifié avant de traiter une image ?','La corrélation entre lésion anatomique et symptomatologie du patient.'],
['Quelle conséquence a une lésion chondrale asymptomatique ?','Elle n’impose pas à elle seule une chirurgie.'],
['Quel est le risque biomécanique d’un fibrocartilage ?','Ses propriétés sont inférieures à celles du cartilage hyalin et sa durabilité est limitée.'],
['Quelle place a le débridement isolé dans une perte de substance ?','Il ne suffit pas à induire spontanément un fibrocartilage dans le defect.'],
['Pourquoi débrider jusqu’à un os sous-chondral saignant avant greffe ?','Pour obtenir un sous-sol receveur favorable à l’intégration.'],
['Quelle limite de la congélation est citée pour l’allogreffe ?','Elle préserve moins bien la viabilité des chondrocytes.'],
['Quel enjeu technique de la mosaïcoplastie conditionne le résultat ?','Restaurer une congruence et une continuité de hauteur cartilagineuse.'],
['Quelle composante du projet thérapeutique ne doit pas être négligée ?','Les attentes d’activité et la motivation du patient.']
].map(([recto, verso]) => ({ recto, verso }));

const I = (enonce, correct, justification) => ({ enonce, is_correct: correct, justification });
const Q = (enonce, items, correction_generale = '') => ({ enonce, items, correction_generale });
const qcm = [
 {label:'QCM 1 — Bilan et indication', questions:[
 Q('Concernant une lésion cartilagineuse focale, quelles caractéristiques soutiennent une indication chirurgicale locale ?', [I('Lésion profonde et symptomatique.',true,'La source limite l’indication aux lésions profondes symptomatiques.'),I('Lésion unique en zone portante.',true,'La conclusion retient une lésion unique et en zone portante.'),I('Lésions en miroir d’arthrose.',false,'Elles sont exclues.'),I('Absence de corrélation clinique.',false,'La symptomatologie doit correspondre à la lésion.'),I('Arthrose avérée.',false,'C’est une contre-indication.')]),
 Q('Le bilan clinique avant réparation cartilagineuse comporte :',[I('L’évaluation de la douleur et des mobilités.',true,'Le bilan fonctionnel les évalue.'),I('L’analyse des activités actuelles et souhaitées.',true,'Le terrain inclut sport et profession.'),I('La recherche d’une instabilité.',true,'Une laxité aggrave le cartilage.'),I('Le choix immédiat d’un implant sans imagerie.',false,'Le bilan est clinique et radiologique.'),I('L’exclusion du poids.',false,'Le poids est un élément du terrain.')]),
 Q('À propos de l’imagerie du genou :',[I('L’arthroscanner aide à cartographier une lésion.',true,'Il est performant pour la cartographie.'),I('L’IRM permet une analyse lésionnelle.',true,'Elle est adaptée avec séquences appropriées.'),I('L’arthroscanner est idéal pour un suivi répété.',false,'Il est invasif et irradiant.'),I('Les radiographies suffisent à toute stadification.',false,'Elles sont surtout significatives pour l’os sous-chondral.'),I('FSE T2 est citée parmi les séquences utiles.',true,'La source cite FSE T2.')]),
 Q('Devant une suspicion de lésion ostéochondrale de cheville :',[I('Les clichés en charge font partie du bilan initial.',true,'Face mortaise et profil en charge sont demandés.'),I('L’IRM peut montrer un œdème médullaire.',true,'C’est un de ses apports.'),I('La scintigraphie peut orienter le dépistage.',true,'Elle peut confirmer ou exclure une lésion.'),I('La recherche de corps libres est inutile.',false,'Elle fait partie de l’analyse radiographique.'),I('Le pincement articulaire ne doit pas être recherché.',false,'Il est recherché.')]),
 Q('Quels facteurs peuvent compromettre une réparation cartilagineuse ?', [I('Défaut d’axe non corrigé.',true,'Il modifie les contraintes.'),I('Laxité articulaire persistante.',true,'Elle dégrade le cartilage.'),I('Arthrose avérée.',true,'Contre-indication rappelée.'),I('Motivation et adhésion au protocole.',true,'Elles participent à la décision.'),I('Une lésion asymptomatique isolée.',false,'Elle ne justifie pas une chirurgie.')])]},
 {label:'QCM 2 — Stimulation sous-chondrale', questions:[
 Q('Les techniques de stimulation sous-chondrale :',[I('Exposent l’os sous-chondral.',true,'C’est leur mécanisme.'),I('Créent un caillot de fibrine.',true,'Le caillot est le support initial.'),I('Visent d’emblée un cartilage hyalin identique.',false,'La réparation est surtout fibrocartilagineuse.'),I('Mobilisent des cellules mésenchymateuses.',true,'Elles migrent depuis l’os spongieux.'),I('Suppriment la nécessité de débrider une lésion instable.',false,'La lésion doit être régularisée.')]),
 Q('À propos des microfractures :',[I('Elles utilisent un poinçon.',true,'Pour éviter le dommage thermique.'),I('Le saignement apporte plaquettes et facteurs de croissance.',true,'Ils participent au caillot.'),I('Le tissu de comblement est majoritairement fibrocartilagineux.',true,'La source le précise.'),I('Elles sont privilégiées pour une forte demande fonctionnelle.',false,'La source les réserve plutôt à faible demande.'),I('Le fibrocartilage se constitue en six à huit semaines.',true,'Délai cité.')]),
 Q('La perforation de Pridie :',[I('Crée une communication avec l’os spongieux.',true,'Mécanisme de la technique.'),I('Favorise la migration de cellules souches.',true,'Elle mobilise les cellules sous-chondrales.'),I('Utilise historiquement une broche de Kirschner.',true,'Instrument cité.'),I('N’a aucun rôle sur la pression intraosseuse.',false,'Elle participe à la décompression.'),I('Produit directement une allogreffe hyaline.',false,'Elle induit une réparation fibrocartilagineuse.')]),
 Q('L’abrasion arthroplastique consiste à :',[I('Utiliser une fraise motorisée.',true,'Geste décrit.'),I('Créer des sillons parallèles de faible profondeur.',true,'Description de la source.'),I('Rechercher un saignement après levée du garrot.',true,'Objectif du geste.'),I('Préserver nécessairement toute la couche sous-chondrale.',false,'La couche séquestrée est excisée.'),I('Autoriser l’appui immédiat sans mobilisation.',false,'Mobilisation sans appui est recommandée.')]),
 Q('Quelle limite doit être expliquée au patient avant stimulation sous-chondrale ?', [I('Le tissu réparateur a des propriétés biomécaniques inférieures.',true,'Le fibrocartilage diffère du cartilage hyalin.'),I('La réparation peut être moins durable.',true,'Conséquence de la nature fibrocartilagineuse.'),I('Elle reconstitue toujours un cartilage hyalin normal.',false,'Ce n’est pas le résultat attendu.'),I('La stratégie dépend aussi du contexte mécanique.',true,'Le terrain et les contraintes comptent.'),I('Le traitement associé des axes et laxités est superflu.',false,'Ils doivent être pris en compte.')])]},
 {label:'QCM 3 — Débridement et lavage', questions:[
 Q('Le lavage articulaire :',[I('Élimine des cytokines et métalloprotéases.',true,'Mécanisme cité.'),I('Retire des débris cartilagineux.',true,'Ils sont retirés.'),I('A un effet essentiellement symptomatique.',true,'Effet réel mais transitoire.'),I('Répare une zone os contre os.',false,'Son effet y est minime.'),I('Peut être répété.',true,'La source le prévoit éventuellement.')]),
 Q('Le débridement cartilagineux vise notamment à :',[I('Retirer les tissus détériorés.',true,'Principe du geste.'),I('Régulariser une lésion avant stimulation.',true,'La lésion est régularisée avant perforations.'),I('Créer à lui seul un fibrocartilage spontané.',false,'Le débridement isolé ne suffit pas.'),I('Participer à un traitement symptomatique précoce.',true,'Il est associé au lavage.'),I('Remplacer l’analyse des lésions associées.',false,'Le bilan reste nécessaire.')]),
 Q('Concernant la durée d’effet du lavage :',[I('Elle est transitoire.',true,'La source le dit.'),I('Elle va de quelques mois à environ un an.',true,'Délai décrit.'),I('Elle est définitive après un seul geste.',false,'Elle est transitoire.'),I('Elle est minime en contact os–os.',true,'Situation de faible bénéfice.'),I('Elle justifie une indication sans symptôme.',false,'Une lésion asymptomatique n’impose pas de chirurgie.')]),
 Q('Les mécanismes proposés du lavage comprennent :',[I('Le renouvellement du liquide synovial.',true,'Mécanisme évoqué.'),I('L’élimination de cristaux irritants.',true,'Cités dans la source.'),I('Une action sur les médiateurs inflammatoires.',true,'Cytokines et métalloprotéases.'),I('La création d’un greffon ostéochondral.',false,'Ce n’est pas le mécanisme.'),I('La distension capsulaire.',true,'Mécanisme invoqué.')]),
 Q('Dans la stratégie de reconstruction, le lavage-débridement :',[I('Ne dispense pas d’identifier une arthrose.',true,'Arthrose reste une contre-indication aux gestes locaux.'),I('Peut améliorer transitoirement les symptômes.',true,'Effet décrit.'),I('Doit être présenté comme une reconstruction hyaline.',false,'Ce n’est pas son objectif.'),I('S’inscrit dans l’évaluation de la congruence.',true,'La stratégie vise la congruence.'),I('Supprime les contraintes mécaniques d’un défaut d’axe.',false,'L’axe doit être traité spécifiquement.')])]},
 {label:'QCM 4 — Greffes ostéochondrales', questions:[
 Q('L’allogreffe ostéochondrale :',[I('Utilise un fragment ostéochondral de donneur.',true,'Principe de l’allogreffe.'),I('Est indiquée pour des pertes de substance volumineuses.',true,'Indication citée.'),I('Exige une compatibilité immunologique HLA.',false,'La source ne demande pas de concordance.'),I('Bénéficie davantage de la fraîcheur du greffon.',true,'Meilleure viabilité chondrocytaire.'),I('Nécessite un sous-sol receveur saignant.',true,'Après débridement.')]),
 Q('La mosaïcoplastie :',[I('Apporte des unités ostéochondrales matures.',true,'C’est une reconstruction structurale.'),I('Peut tenir par press-fit.',true,'Effet de coin.'),I('Peut nécessiter un vissage enfoui.',true,'Si stabilisation complémentaire.'),I('Ignore les défauts d’axe.',false,'Ils doivent être corrigés.'),I('Vise une congruence de surface.',true,'Hauteur et continuité doivent être restaurées.')]),
 Q('Après greffe ostéochondrale, la rééducation comporte :',[I('Une décharge initiale.',true,'Quatre à huit semaines selon cas.'),I('Une reprise progressive de l’appui.',true,'Après décharge.'),I('La mobilisation des amplitudes sans danger pour la greffe.',true,'Mentionnée dans la source.'),I('Un appui maximal immédiat systématique.',false,'Décharge initiale.'),I('Une adaptation à la localisation.',true,'Durée selon taille et localisation.')]),
 Q('À la cheville, la mosaïcoplastie :',[I('Répond aux mêmes règles rigoureuses qu’au genou.',true,'Source.'),I('Peut imposer un abord transmalléolaire.',true,'Pour exposer la lésion.'),I('Est toujours réalisable par voie arthroscopique simple.',false,'L’exposition peut être insuffisante.'),I('Nécessite un greffon perpendiculaire à la lésion.',true,'Difficulté justifiant parfois l’ouverture.'),I('N’a aucun risque de morbidité donneuse.',false,'La morbidité du site donneur est une limite.')]),
 Q('Quels paramètres conditionnent le succès d’une mosaïcoplastie ?', [I('Indications correctement posées.',true,'La source insiste sur indications/contre-indications.'),I('Absence de laxité non traitée.',true,'Laxité est délétère.'),I('Absence de désaxation non corrigée.',true,'Les contraintes doivent être corrigées.'),I('Qualité de l’abord de la lésion.',true,'Exposition nécessaire.'),I('Présence d’arthrose installée.',false,'Contre-indication.')])]},
 {label:'QCM 5 — Réparation cellulaire', questions:[
 Q('La première génération de chondrocytes autologues :',[I('Implante des cellules cultivées sous un patch périosté.',true,'Principe décrit.'),I('Nécessite un prélèvement de cartilage sain.',true,'Premier temps.'),I('Évite tout second geste opératoire.',false,'Implantation secondaire.'),I('Utilise une colle de fibrine pour l’étanchéité.',true,'Technique décrite.'),I('Expose à une hypertrophie périostée.',true,'Complication citée.')]),
 Q('Les matrices de deuxième génération :',[I('Ont été développées pour éviter les problèmes du périoste.',true,'Raison de leur développement.'),I('Peuvent être protéiques.',true,'Exemple de catégorie.'),I('Peuvent être polysaccharidiques.',true,'Exemple de catégorie.'),I('Suppriment nécessairement toute culture cellulaire.',false,'Les délais de culture sont comparables.'),I('Peuvent faire appel à l’acide hyaluronique.',true,'Molécule citée.')]),
 Q('Un scaffold de troisième génération doit être :',[I('Biocompatible.',true,'Propriété attendue.'),I('Biodégradable.',true,'Propriété attendue.'),I('Perméable.',true,'Propriété attendue.'),I('Dépourvu d’activité biologique.',false,'Il doit être bioactif.'),I('Compatible avec la synthèse de matrice extracellulaire.',true,'Objectif biologique.')]),
 Q('La troisième génération comprend :',[I('Un premier temps d’évaluation et prélèvement.',true,'Phase 1.'),I('Une culture cellulaire sur matrice 3D.',true,'Phase 2.'),I('Une implantation secondaire.',true,'Phase 3.'),I('Une mise en appui complet dès le lendemain.',false,'Absence d’appui initiale.'),I('La recherche d’une surface sans marche d’escalier.',true,'Objectif technique.')]),
 Q('Après implantation de chondrocytes :',[I('La mobilisation passive fait partie du protocole.',true,'Source.'),I('L’absence d’appui est initialement prescrite.',true,'Source.'),I('La reprise d’activité est immédiate.',false,'Elle est tardive.'),I('Le suivi doit intégrer l’adhésion du patient.',true,'Projet thérapeutique.'),I('Les complications du patch périosté sont impossibles.',false,'Plusieurs sont citées.')])]},
 {label:'QCM 6 — Stratégie au genou', questions:[
 Q('Au genou, avant un geste cartilagineux, il faut :',[I('Corriger une laxité par reconstruction ligamentaire.',true,'Préalable cité.'),I('Considérer une ostéotomie si défaut d’axe.',true,'La réaxation est indiquée selon le défaut.'),I('Vérifier l’état méniscal.',true,'Éléments associés à évaluer.'),I('Ignorer la demande fonctionnelle.',false,'Elle guide le choix.'),I('Corréler l’imagerie aux symptômes.',true,'Principe de conclusion.')]),
 Q('Dans l’algorithme lésionnel du genou :',[I('Les petites lésions peuvent relever de microfractures ou mosaïcoplastie.',true,'Arbre décisionnel source.'),I('Les lésions intermédiaires peuvent relever de CCA troisième génération.',true,'Place évoquée entre 2 et 4 cm².'),I('Les grandes pertes peuvent conduire à allogreffe ou méga-OATS.',true,'Au-delà de 4 cm².'),I('La taille est le seul paramètre décisionnel.',false,'Terrain et mécanique comptent.'),I('L’arthrose est une indication de greffe locale.',false,'Contre-indication.')]),
 Q('Quels facteurs doivent être discutés avec un sportif avant réparation ?', [I('Niveau d’activité souhaité.',true,'Évaluation du terrain.'),I('Motivation pour le protocole.',true,'Facteur de décision.'),I('Poids.',true,'Facteur de terrain.'),I('Absence de toute imagerie.',false,'Bilan indispensable.'),I('Stabilité articulaire.',true,'Facteur de dégradation.')]),
 Q('Concernant la littérature des techniques cartilagineuses :',[I('Beaucoup de données sont rétrospectives.',true,'Source.'),I('Le niveau de preuve est parfois faible.',true,'Absence de niveau 1 ou 2 pour certaines techniques.'),I('Toute indication est parfaitement consensuelle.',false,'Certaines indications restent discutées.'),I('La prudence envers les techniques émergentes est recommandée.',true,'Conclusion.'),I('L’accessibilité locale peut influer sur la stratégie.',true,'Source.')]),
 Q('Quelle formulation est juste ?', [I('La mosaïcoplastie est une référence en France.',true,'Conclusion.'),I('Elle est techniquement délicate.',true,'Conclusion.'),I('Les microfractures ont une place si faible demande fonctionnelle.',true,'Conclusion.'),I('Un seul procédé convient à toutes les lésions.',false,'Chaque cas doit être individualisé.'),I('Le projet patient est secondaire.',false,'Il est central.')])]},
 {label:'QCM 7 — Stratégie à la cheville', questions:[
 Q('Pour une lésion ostéochondrale talienne, la source recommande :',[I('Une tentative de traitement conservateur initial.',true,'Première intention.'),I('Un bilan en charge.',true,'Clichés initiaux.'),I('Une analyse de l’os sous-chondral.',true,'Bilan morphologique.'),I('Une chirurgie urgente pour toute lésion découverte.',false,'Le traitement peut être différé.'),I('Une adaptation à la demande fonctionnelle.',true,'Arbre décisionnel.')]),
 Q('Lorsque le cartilage talien de surface est intact :',[I('La perforation rétrograde est indiquée.',true,'Indication citée.'),I('Le franchissement de la surface articulaire est recherché.',false,'Il doit être évité.'),I('Un contrôle radioscopique est utile.',true,'Source.'),I('Un kyste important peut justifier une greffe osseuse associée.',true,'Source.'),I('L’IRM est sans intérêt.',false,'Elle renseigne sur les lésions et l’œdème.')]),
 Q('Les limites des techniques traditionnelles à la cheville concernent :',[I('La taille de la lésion.',true,'Limite rapportée.'),I('L’atteinte de l’os sous-chondral.',true,'Un sous-sol insuffisant limite la stimulation.'),I('L’âge avancé.',true,'Contre-indication évoquée.'),I('L’arthrose préexistante.',true,'Contre-indication.'),I('La nécessité de toute imagerie.',false,'L’imagerie reste indispensable.')]),
 Q('Une lésion talienne étendue de plus de 2,5 cm² :',[I('Est difficilement considérée comme focale.',true,'Source.'),I('Doit faire discuter un contexte arthrosique.',true,'Source.'),I('Relève automatiquement de microfractures simples.',false,'La stratégie dépend de profondeur et contexte.'),I('Nécessite une réévaluation globale.',true,'Conséquence de la stratégie.'),I('Est indépendante de l’état articulaire.',false,'L’état articulaire est déterminant.')]),
 Q('L’abord d’une mosaïcoplastie talienne :',[I('Doit permettre une introduction perpendiculaire des greffons.',true,'Principe technique.'),I('Peut nécessiter une ostéotomie malléolaire.',true,'Selon topographie.'),I('Dépend de la localisation de la lésion.',true,'Exposition variable.'),I('Est toujours identique au genou.',false,'Cheville impose des contraintes d’abord.'),I('Ignore les structures tendineuses et nerveuses.',false,'Elles sont protégées lors de l’abord.')])]},
 {label:'QCM 8 — Principes transversaux', questions:[
 Q('Une stratégie de reconstruction cartilagineuse de qualité repose sur :',[I('Analyse lésionnelle et imagerie adaptée.',true,'Premier axe de conclusion.'),I('Évaluation ligamentaire et méniscale.',true,'Deuxième axe.'),I('Corrélation clinique-imagerie.',true,'Troisième axe.'),I('Choix imposé par la seule disponibilité d’un implant.',false,'Décision individualisée.'),I('Prise en compte de l’adhésion du patient.',true,'Facteur important.')]),
 Q('Les lésions associées doivent être :',[I('Traitées avant la réparation cartilagineuse si nécessaires.',true,'Ligament et axe d’abord.'),I('Réévaluées après une période d’observation.',true,'Trois à six mois cités.'),I('Ignorées si la lésion est visible à l’IRM.',false,'Elles conditionnent le résultat.'),I('Intégrées au projet de préservation articulaire.',true,'Source.'),I('Considérées avec le morphotype global.',true,'Source.')]),
 Q('Quelles contre-indications sont mises en avant ?', [I('Arthrose avérée.',true,'Contre-indication.'),I('Obésité morbide.',true,'Contre-indication rappelée.'),I('Laxité non corrigée.',true,'Contre-indication mécanique.'),I('Défaut d’axe non corrigé.',true,'Contre-indication mécanique.'),I('Lésion profonde symptomatique isolée.',false,'C’est au contraire le profil candidat.')]),
 Q('Pourquoi individualiser la décision ?', [I('Les lésions et leurs contraintes mécaniques diffèrent.',true,'Mécanique et morphologie comptent.'),I('L’âge et l’activité modifient le bénéfice attendu.',true,'Conclusion.'),I('Les techniques n’ont pas toutes le même niveau de preuve.',true,'Littérature hétérogène.'),I('Le patient ne participe jamais à la décision.',false,'Motivation et adhésion sont cruciales.'),I('Les ressources locales peuvent être limitées.',true,'Accessibilité locale citée.')]),
 Q('Quelle attitude pédagogique est conforme à la source ?', [I('Distinguer réparation fibrocartilagineuse et régénération hyaline.',true,'Objectifs différents.'),I('Expliquer les limites de chaque option.',true,'Prudence recommandée.'),I('Promettre une restitution certaine du cartilage normal.',false,'Résultats variables.'),I('Préparer le patient aux suites sans appui.',true,'Suites détaillées.'),I('Intégrer le suivi fonctionnel au résultat.',true,'Bilan chiffré avant/après.')])]},
];

const dpQuestion = (enonce, right, wrong1, wrong2, wrong3, wrong4) => Q(enonce,[I(right,true,'Compatible avec les données du cas et les principes du corpus.'),I(wrong1,false,'Cette proposition ne correspond pas à la stratégie source.'),I(wrong2,false,'Cette proposition ne répond pas aux critères de ce temps.'),I(wrong3,false,'Cette proposition est contraire aux limites ou contre-indications décrites.'),I(wrong4,false,'Cette proposition n’est pas justifiée par les données disponibles.')]);
const dpSpecs = [
 ['DP 1 — Lésion fémorale focale chez un sportif','Un homme de 24 ans, footballeur amateur, consulte pour douleur du genou droit à la course et aux escaliers depuis un traumatisme rotatoire. L’IRM montre une lésion chondrale focale profonde du condyle fémoral médial en zone portante. Il n’a pas d’arthrose radiographique, son axe est neutre et le genou est stable. Il souhaite reprendre le sport, accepte une période de décharge et un suivi fonctionnel.','Confirmer le caractère symptomatique et profond de la lésion','Traiter l’IRM isolée sans interrogatoire','Conclure à une arthrose en miroir','Écarter tout bilan de stabilité','Promettre un résultat définitif immédiat'],
 ['DP 2 — Lésion avec désaxation','Une femme de 34 ans, active professionnellement, présente une douleur médiale du genou gauche persistante. Elle a une lésion cartilagineuse profonde du condyle médial ; les radiographies de l’axe objectivent un varus et l’examen retrouve une gêne à la marche. L’IRM n’évoque pas d’arthrose diffuse. Elle est motivée pour une stratégie en plusieurs temps avec contrôle radioclinique et reprise d’appui progressive.','Prendre en charge le défaut d’axe avant la réparation cartilagineuse','Négliger le varus car la lésion est focale','Faire une microfracture sans bilan mécanique','Assimiler toute douleur à une arthrose diffuse','Autoriser la reprise sportive sans suivi'],
 ['DP 3 — Débridement et microfractures','Un homme de 42 ans, peu sportif, a une lésion chondrale profonde focalisée du genou découverte après gonalgies mécaniques. Le bilan ne retrouve ni laxité, ni désaxation, ni arthrose. Une arthroscopie diagnostique confirme un cartilage instable avec perte de substance limitée. Il comprend les limites de la réparation fibrocartilagineuse et accepte la décharge et le suivi des symptômes.','Régulariser la lésion puis discuter une stimulation sous-chondrale','Viser obligatoirement un cartilage hyalin identique','Conserver les berges instables','Ignorer la faible demande fonctionnelle','Prescrire un appui maximal immédiat'],
 ['DP 4 — Grande perte ostéochondrale','Une femme de 30 ans présente une douleur invalidante du genou après traumatisme ancien. L’imagerie montre une perte de substance ostéochondrale volumineuse localisée, sans arthrose diffuse ; axe et stabilité sont corrigés. Elle est informée des contraintes de disponibilité tissulaire, de l’intégration du greffon et du protocole de décharge. Un suivi clinique et radiographique est programmé.','Discuter une reconstruction ostéochondrale structurale','Limiter la réflexion à un lavage symptomatique','Choisir une microfracture comme unique réponse certaine','Oublier la viabilité du greffon','Supprimer toute surveillance postopératoire'],
 ['DP 5 — Lésion ostéochondrale du talus','Un homme de 27 ans, travailleur manuel, présente une douleur de cheville après entorse ancienne. Les clichés en charge et l’IRM identifient une lésion ostéochondrale du dôme talien avec cartilage de surface intact et kyste sous-chondral. Il n’a pas d’arthrose clinique. Une période de traitement conservateur a été menée ; il accepte un contrôle radioclinique et une reprise d’appui progressive.','Envisager une perforation rétrograde en préservant la surface','Traverser volontairement le cartilage sain','Négliger le kyste sous-chondral','Décider sans imagerie en charge','Écarter tout traitement conservateur préalable'],
 ['DP 6 — Culture chondrocytaire','Une femme de 29 ans, coureuse, a une lésion focale profonde du condyle fémoral après traumatisme, sans laxité ni désaxation. Après information, elle accepte un protocole long avec prélèvement de cartilage sain, culture cellulaire, second geste et rééducation sans appui. Elle souhaite comprendre le rôle des matrices et les risques des anciennes techniques sous périoste ; un suivi à long terme est prévu.','Présenter une stratégie de régénération par chondrocytes autologues','Confondre culture cellulaire et lavage articulaire','Promettre une chirurgie en un temps sans rééducation','Ignorer la motivation de la patiente','Annoncer l’absence de complication possible'],
 ['DP 7 — Lésion associée à laxité','Un adolescent de 18 ans présente une douleur et des épisodes de dérobement du genou après rupture ancienne du ligament croisé. L’IRM retrouve une lésion chondrale localisée et l’examen confirme une instabilité. Il n’existe pas d’arthrose mais il souhaite reprendre le pivot-contact. Il est prêt à suivre une prise en charge séquentielle, la rééducation, puis les contrôles fonctionnels avant décision cartilagineuse.','Traiter l’instabilité avant une réparation cartilagineuse','Faire abstraction des épisodes de dérobement','Choisir une technique seulement selon l’IRM','Autoriser la reprise pivot immédiate','Considérer la laxité comme bénéfique'],
 ['DP 8 — Lésion étendue dans un contexte arthrosique','Un homme de 55 ans présente une gonalgie progressive, une limitation de marche et des lésions cartilagineuses en miroir avec pincement articulaire. L’IRM complète le bilan mais l’examen souligne une atteinte diffuse et un surpoids important. Il demande une « réparation du cartilage » ; une consultation de suivi est prévue pour expliquer le projet de prise en charge global et les limites des gestes locaux.','Écarter une réparation focale isolée dans ce contexte arthrosique','Présenter une microfracture comme réparation durable garantie','Négliger l’obésité morbide','Considérer les lésions en miroir comme une bonne indication','Dissocier la décision de la symptomatologie']
];
const dp = dpSpecs.map(([label,vignette,good,w1,w2,w3,w4],idx)=>({label,vignette,questions:[
 dpQuestion('Quelle est la priorité du bilan initial ?',good,w1,w2,w3,w4),
 dpQuestion('Nouvel élément : le bilan d’axe et de stabilité est relu. Quelle conséquence thérapeutique est la plus cohérente ?', idx===1?'Corriger le défaut mécanique avant le geste cartilagineux':idx===6?'Planifier la reconstruction ligamentaire avant le geste cartilagineux':idx===7?'Ne pas proposer un geste local de réparation focale':'Vérifier qu’aucune contre-indication mécanique ou arthrosique ne persiste','Ignorer les données mécaniques','Décider sur la seule taille de la lésion','Retarder toute évaluation clinique','Assimiler une lésion focale à une arthrose'),
 dpQuestion('Nouvel élément : l’imagerie précise la topographie et l’os sous-chondral. Quel examen est utile pour compléter la cartographie selon l’articulation ?',idx===4?'IRM et imagerie en charge adaptées à la cheville':'IRM ou arthroscanner selon la question morphologique','Aucun examen complémentaire','Seulement une imagerie sans analyse clinique','Un examen ne tenant pas compte de l’os sous-chondral','Une imagerie répétée invasive sans indication'),
 dpQuestion('Nouvel élément : le patient demande le principe du geste envisagé. Quelle explication est juste ?',idx===2?'La stimulation sous-chondrale induit surtout un fibrocartilage':idx===3?'Une greffe structurale apporte une unité ostéochondrale mature':idx===4?'La perforation rétrograde vise la lésion en préservant le cartilage intact':idx===5?'Les chondrocytes sont prélevés, cultivés puis implantés sur un support':'Le geste restaure toujours un cartilage hyalin identique','Le geste dispense de débridement','Le geste corrige à lui seul tout défaut d’axe','Le résultat ne dépend pas du terrain','Le choix est indépendant de la demande fonctionnelle'),
 dpQuestion('Nouvel élément : les suites sont discutées. Quelle consigne est cohérente ?',idx===2?'Prévoir une décharge et une mobilisation adaptée':idx===5?'Prévoir mobilisation passive et absence d’appui initiale':'Prévoir une reprise d’appui progressive après la phase protégée','Appui maximal immédiat','Absence de suivi fonctionnel','Arrêt de toute mobilisation sans réévaluation','Reprise sportive sans délai'),
 dpQuestion('Nouvel élément : un contrôle à distance est organisé. Quel résultat doit-il intégrer ?', 'La douleur, les mobilités et les activités fonctionnelles du patient','La seule apparence d’une image','Une promesse de retour identique sans bilan','L’absence d’interrogatoire du patient','Un résultat indépendant des symptômes'),
 dpQuestion('Nouvel élément : le patient souhaite reprendre son activité. Quelle information est essentielle ?', 'La reprise dépend du geste, de la rééducation, de la demande fonctionnelle et du suivi','Une reprise identique et immédiate pour tous','L’activité n’influence jamais l’indication','La motivation est inutile','Le protocole peut être abandonné après la chirurgie')
] }));

const series = [...qcm, ...dp];
for (const serie of series) {
  for (const question of serie.questions) {
    question.items.forEach((item, index) => { item.lettre = 'ABCDE'[index]; });
  }
}
const fiche = JSON.parse(readFileSync(join(draftDir,'fiche.model.json'),'utf8'));
const doc = { title: fiche.title, provenance:{extract:'extract.json',sourceOnly:true,clinicalFraming:'Cartes, QCM et dossiers progressifs rédigés séparément à partir des blocs source.'}, flashcards:facts, series };
writeFileSync(join(out,'chapter.json'), JSON.stringify(doc,null,2)+'\n','utf8');
copyFileSync(join(draftDir,'fiche.html'),join(out,'fiche.html'));
copyFileSync(join(draftDir,'fiche.body.html'),join(out,'fiche.body.html'));
copyFileSync(join(draftDir,'fiche.model.json'),join(out,'fiche.model.json'));
writeFileSync(join(out,'coverage.json'),JSON.stringify({sourceBlocks:[9,20,25,29,31,34,40,42,44,50,51,56,68,70,76,131,134,135,137,139,152,161,171,182,184],flashcards:facts.length,qcmQuestions:40,dpQuestions:56,items:480},null,2)+'\n','utf8');
console.log(JSON.stringify({out,flashcards:facts.length,series:series.length,questions:series.reduce((n,s)=>n+s.questions.length,0)}));
