import { emitOrthopediePackage } from './lib/orthopedie-package.mjs';

// Chapitre 66 — rédaction source-only.  Ce fichier est une copie de travail
// structurée, pas un transformateur cartes -> QCM : chaque banque est écrite
// dans son propre tableau ci-dessous et renvoie aux blocs d'extraction cités.
const chapterDir = 'C:/Users/Admin/Desktop/Major-ecn-projects/.corpus-orthopedie/membre-superieur-de-l-hemiplegique';
const outputDir = `${chapterDir}/delivery/source-quality-ch66-2026-08-10`;
const B = (text, children) => children ? { text, children } : text;

const fiche = {
  title: 'Membre supérieur de l’hémiplégique', year: '2025-2026',
  coverSubtitle: 'Neuro-orthopédie — évaluation et indications chirurgicales',
  sourceBlocks: [10,12,13,17,18,19,20,25,30,33,35,37,44,46,50,61,65,70,82,84,87,88,99,101,105,115,117,143,144,154,161,164,183,188,200,203,204,205,206,208,218,219,220,226,227,231,249,251,281,282,283,284,285,286],
  parts: [
    { title: 'Comprendre le tableau neurologique', sections: [
      { title: 'Déficit central et conséquences secondaires', rows: [
        { concept: 'Triade lésionnelle', marker: 'yield', bullets: [B('Déficit de commande volontaire, particulièrement des extenseurs du coude, du poignet et des doigts.'), B('Levée d’inhibition du réflexe myotatique : spasticité des adducteurs-rotateurs internes d’épaule et des fléchisseurs.'), B('Désorganisation du schéma moteur : synergie agonistes–antagonistes altérée.') ] },
        { concept: 'Évolution des déséquilibres', bullets: [B('Les muscles spastiques se rétractent progressivement.'), B('Les antagonistes s’affaiblissent face aux muscles spastiques.'), B('Les attitudes vicieuses fixées inhibent le schéma moteur résiduel.') ] },
        { concept: 'Profils étiologiques', bullets: [B('Paralysie cérébrale : atteinte précoce, souvent diffuse et extrapyramidale ; potentiel de récupération plus important.'), B('Cérébrolésion acquise : cerveau mature, récupération limitée ; objectifs fonctionnels souvent plus restreints.'), B('La stratégie du membre supérieur repose toutefois sur des principes communs.') ], image: { path: 'img/img_001.png', position: 'before', size: 'small' } }
      ] },
      { title: 'Objectifs réalistes du programme', rows: [
        { concept: 'Chirurgie fonctionnelle', marker: 'ecn', bullets: [B('Objectif : améliorer la préhension et le positionnement de la main dans l’espace.'), B('Elle suppose une commande proximale utilisable et des fléchisseurs mobilisables.'), B('La correction d’une déformation peut rendre un schéma moteur de nouveau exploitable.') ] },
        { concept: 'Chirurgie non fonctionnelle', bullets: [B('Objectifs : hygiène, nursing et apparence esthétique.'), B('Elle est indiquée lorsque le schéma moteur proximal est médiocre et que les fléchisseurs des doigts et du pouce font défaut.'), B('Elle reste utile au patient même sans restitution de préhension.') ] },
        { concept: 'Logique de décision', marker: 'trap', bullets: [B('Il n’existe pas de codification rigide : le programme est individualisé.'), B('Une attitude vicieuse fixe peut justifier une correction précoce pour débloquer la rééducation.'), B('Un même temps opératoire peut traiter plusieurs segments car leurs fonctions sont liées.') ] }
      ] }
    ] },
    { title: 'Bilan préopératoire et choix des gestes', sections: [
      { title: 'Évaluation globale et répétée', rows: [
        { concept: 'Organisation du bilan', marker: 'ecn', bullets: [B('Bilan global : ne pas limiter l’analyse au membre supérieur.'), B('Bilan collectif : intégrer équipe médicale, paramédicale, patient et entourage.'), B('Bilan répété : la spasticité varie selon le temps et les situations.') ] },
        { concept: 'Paramètres par segment', bullets: [B('Apprécier séparément motricité volontaire, spasticité et rétraction.'), B('Analyser la qualité du schéma moteur et l’impact fonctionnel de chaque attitude.'), B('Fixer avec le patient un contrat d’objectifs avant le programme chirurgical.') ] },
        { concept: 'Tests utiles', bullets: [B('Les blocs anesthésiques distinguent spasticité et rétraction.'), B('Les injections de toxine botulinique et l’EMG contribuent à l’analyse de certains déficits.'), B('Le bloc peut aussi mesurer le prix fonctionnel d’une dénervation.') ] }
      ] },
      { title: 'Quatre leviers thérapeutiques', rows: [
        { concept: 'Réduire la spasticité', bullets: [B('Hyponeurotisation ou dénervation : agir sur l’innervation d’un muscle spastique.'), B('Prérequis : muscle causal identifié et pédicule moteur individualisable.'), B('Une dénervation ne corrige pas une rétraction ; une réinnervation de voisinage peut réduire l’effet dans le temps.') ] },
        { concept: 'Détendre et conserver', bullets: [B('Les allongements corrigent la rétraction et déplacent la courbe tension–longueur.'), B('Ils réduisent aussi la spasticité mais peuvent affaiblir la commande volontaire.'), B('La désinsertion proximale est réservée à un muscle rétracté dont une fonction est conservée.') ] },
        { concept: 'Renforcer ou stabiliser', bullets: [B('Un transfert exige un moteur à commande saine et une fonction substituable.'), B('La réduction de la spasticité des antagonistes est indispensable avant transfert.'), B('L’arthrodèse simplifie une chaîne polyarticulaire, corrige une attitude ou stabilise un segment.') ], image: { path: 'img/img_003.png', position: 'after', size: 'small' } }
      ] }
    ] },
    { title: 'Épaule, coude et avant-bras', sections: [
      { title: 'Épaule : stabilité et ouverture', rows: [
        { concept: 'Subluxation glénohumérale inférieure', bullets: [B('Indication : subluxation persistante, symptomatique et douloureuse après la phase flaccide.'), B('Évaluer la réductibilité et la régression de la douleur après réduction.'), B('Une subluxation fixée contre-indique la suspension par parties molles.') ], image: { path: 'img/img_002.png', position: 'before', size: 'small' } },
        { concept: 'Attitude en adduction–rotation interne', bullets: [B('Indication chirurgicale : retentissement fonctionnel majeur avec main fonctionnelle, ou impossibilité de nursing axillaire.'), B('Le bloc de l’anse des pectoraux aide à différencier spasticité et rétraction.'), B('Libération progressive : pectoralis major puis subscapularis, en respectant la capsule.') ] },
        { concept: 'Arthrodèse glénohumérale', bullets: [B('Exceptionnelle chez le cérébrolésé car elle peut gêner le nursing.'), B('Discutée devant une luxation fixée douloureuse ou une épaule très déficitaire avec bonne fonction distale.'), B('La rotation interne est adaptée pour privilégier l’accès aux objets devant le patient.') ] }
      ] },
      { title: 'Flessum du coude et pronation', rows: [
        { concept: 'Analyser un flessum du coude', marker: 'yield', bullets: [B('Les causes prédominantes sont : biceps brachial, brachial antérieur, brachioradialis puis épitrochléens.'), B('Les variations avec la supination explorent le biceps ; la palpation explore le brachioradialis.'), B('Le bloc du nerf musculocutané différencie spasticité, rétraction et rôle fonctionnel du brachioradialis.') ], image: { path: 'img/img_004.png', position: 'before', size: 'small' } },
        { concept: 'Choisir le geste du coude', bullets: [B('Spasticité importante du biceps sans rétraction marquée : neurotomie du nerf musculocutané.'), B('Déformation dynamique avec fonction préservée : allongement à la jonction tendinomusculaire.'), B('Flessum statique sévère : gestes tendineux plus affaiblissants ; conserver un flessum résiduel si le risque vasculaire le justifie.') ] },
        { concept: 'Attitude en pronation', bullets: [B('Une pronation fixée compromet les prises bimanuelles et les prises pollici- ou palmodigitales.'), B('Absence de supination au-delà du neutre : indication de prise en charge chirurgicale.'), B('Supination résiduelle : ténotomie du pronator quadratus ± détente des épitrochléens ; rond pronateur actif avec déformation souple : transfert supinateur.') ] }
      ] }
    ] },
    { title: 'Poignet et doigts longs', sections: [
      { title: 'Capotage du poignet', rows: [
        { concept: 'Bilan fonctionnel', marker: 'ecn', bullets: [B('Le capotage en flexion est l’attitude la plus fréquente ; l’hyperextension est rare.'), B('Rechercher une extension active du poignet et des doigts : déficit réel ou frein par spasticité/rétraction des fléchisseurs.'), B('Évaluer un moteur transférable, notamment le FCU, et l’effet des blocs anesthésiques.') ] },
        { concept: 'Préserver la mobilité', bullets: [B('Des extenseurs actifs révélés au bloc autorisent une détente des fléchisseurs du poignet.'), B('Le transfert du FCU sur l’ECRB est envisagé si la commande du FCU est saine.'), B('La résection de première rangée se discute pour un poignet enraidi avec fléchisseurs et extenseurs fonctionnels modérément spastiques.') ], image: { path: 'img/img_012.png', position: 'after', size: 'large' } },
        { concept: 'Stabiliser le poignet', bullets: [B('Les gestes non conservateurs ne signifient pas nécessairement une main non fonctionnelle.'), B('Lorsque la synergie poignet–doigts est irréalisable, la stabilisation peut permettre une prise rudimentaire.'), B('Après résection de première rangée : contention rigide et contrôles radiologiques réguliers.') ] }
      ] },
      { title: 'Ouverture des doigts longs', rows: [
        { concept: 'Principes', bullets: [B('Les fléchisseurs et le pouce conservent parfois une ébauche de commande mais sont souvent spastiques ou rétractés.'), B('L’ouverture impose souvent une réanimation des extenseurs, rarement actifs spontanément.'), B('La spasticité intrinsèque peut être masquée par l’enroulement extrinsèque.') ] },
        { concept: 'Détente des fléchisseurs', bullets: [B('Les gestes possibles sont neurologiques, tendineux d’allongement ou de transfert.'), B('Les meilleurs candidats à l’hyponeurotisation sont peu rétractés, améliorés par toxine botulinique et dotés d’antagonistes.'), B('Le transfert des FDS sur les FDP permet un allongement des fléchisseurs en les synchronisant.') ], image: { path: 'img/img_013.png', position: 'after', size: 'large' } },
        { concept: 'Réanimer l’extension', bullets: [B('FCU ou FCR peuvent réanimer l’EDC si leur commande est saine.'), B('Le transfert est réglé pour obtenir l’extension des métacarpophalangiennes avec poignet en rectitude.'), B('FCR ou PL peuvent améliorer l’ouverture pouce–index par transfert sur EPL ou APL.') ] }
      ] }
    ] },
    { title: 'Intrinsèques et pouce dans la paume', sections: [
      { title: 'Intrinsèques des doigts longs', rows: [
        { concept: 'Reconnaître la rétraction', marker: 'yield', bullets: [B('Les intrinsèques spastiques entraînent flexion des MCP et extension des IP.'), B('La manœuvre de Bunnel compare la flexion des IPP selon la position des MCP.'), B('Une flexion des IPP améliorée lorsque les MCP fléchissent signe une rétraction intrinsèque.') ] },
        { concept: 'Trois options', bullets: [B('Ténotomie/allongement distal : agit sur rétraction et spasticité.'), B('Dénervation : agit sur la spasticité, non sur la rétraction.'), B('Désinsertion proximale : agit sur les deux composantes.') ], image: { path: 'img/img_020.png', position: 'before', size: 'small' } },
        { concept: 'Neurotomie ulnaire', marker: 'trap', bullets: [B('Indication : spasticité intrinsèque sans rétraction, souvent après détente des extrinsèques.'), B('Contre-indication : pince pollicidigitale potentiellement fonctionnelle dépendant de l’adductor brevis.'), B('Le neurostimulateur identifie la branche motrice profonde et vérifie l’efficacité du geste.') ] }
      ] },
      { title: 'Thumb in the palm : stratégie séquentielle', rows: [
        { concept: 'Décomposer la déformation', marker: 'ecn', bullets: [B('FPL : flexion IP et MCP avec enroulement dans la paume ; FPB : flexion MCP.'), B('Adducteur et premier interosseux dorsal : fermeture de la première commissure.'), B('Déficit EPL/APL/EPB et rétraction cutanée de commissure participent à l’absence d’ouverture.') ] },
        { concept: 'Bilan par blocs', bullets: [B('Bloc ulnaire au poignet : spasticité de l’adducteur et du FPB.'), B('Bloc médian au poignet : composante thénarienne.'), B('Bloc médian au coude : composante spastique du FPL.') ] },
        { concept: 'Corriger les composantes', bullets: [B('Allonger le FPL spastique ou rétracté sans excès pour éviter une hyperextension IP.'), B('Plastie si rétraction cutanée de première commissure ; stabiliser la MCP si hyperextension.'), B('Transfert FCR, PL ou FPL sur EPL ou premier métacarpien pour une ouverture active ; arthrodèse trapézométacarpienne si besoin.') ], image: { path: 'img/img_022.png', position: 'after', size: 'large' } }
      ] }
    ] }
  ],
  synthesis: {
    chiffres: { headers: ['Repère clinique', 'Décision'], rows: [['3 facteurs absents', 'Mauvais schéma proximal + absence des fléchisseurs des doigts et du pouce : objectif non fonctionnel'], ['Poignet en flexion de 20°', 'Position de test de l’extension active des doigts longs'], ['MCP instables après désinsertion', 'Broche temporaire possible pendant 4 semaines'], ['Après arthrodèse TM', 'Orthèse de protection pendant 6 semaines']] },
    tables: [
      { title: 'Lire la déformation avant le geste', headers: ['Situation', 'Test décisif', 'Conséquence'], rows: [['Flessum du coude', 'Bloc musculocutané', 'Spasticité ou rétraction ; mesurer le rôle du BR'], ['Pronation', 'Supination active/passive', 'Détente PQ, transfert du RP ou ténotomie du PT'], ['Main fermée', 'Blocs médian puis ulnaire', 'Démasquer les intrinsèques et protéger une pince utile'], ['Pouce en paume', 'Blocs ulnaire/médian', 'Identifier FPL, thénar, adducteur et première commissure']] },
      { title: 'Gestes : ce qu’ils corrigent', headers: ['Geste', 'Spasticité', 'Rétraction', 'Point de vigilance'], rows: [['Dénervation', 'Oui', 'Non', 'Perte d’effet et coût fonctionnel'], ['Allongement', 'Oui', 'Oui', 'Affaiblit la commande active'], ['Désinsertion proximale', 'Oui', 'Oui', 'Fonction musculaire à préserver'], ['Transfert', 'Non directement', 'Non directement', 'Moteur à commande saine et antagonistes contrôlés'], ['Arthrodèse', 'Stabilise', 'Corrige une attitude', 'Simplifie la chaîne au prix de mobilité']] }
    ],
    keyPoints: ['Le bilan est global, collectif et répété.', 'Distinguer spasticité, rétraction et déficit moteur par l’examen et les blocs.', 'L’objectif fonctionnel exige commande proximale et fléchisseurs mobilisables.', 'Une dénervation ne corrige jamais une rétraction.', 'Un transfert ne se conçoit qu’avec un moteur à commande saine.', 'Une stabilisation du poignet peut améliorer une prise rudimentaire.', 'La pince pollicidigitale résiduelle protège d’une neurotomie ulnaire.'],
    eclair: ['Toujours partir d’un objectif : préhension ou hygiène/nursing.', 'Bilan segmentaire : commande, spasticité, rétraction, schéma moteur.', 'Blocs anesthésiques : test thérapeutique et pronostique.', 'Coude : biceps/BA/BR ; prudence dans les flessums fixés sévères.', 'Poignet : distinguer extenseurs absents d’extenseurs freinés.', 'Main : démasquer les intrinsèques après détente des extrinsèques.', 'Pouce en paume : corriger chaque composante, sans sacrifier une pince utile.']
  }
};

const card = (recto, verso) => ({ recto, verso });
const facts = [
  card('Quels extenseurs sont particulièrement déficitaires ?', 'Doigts<br>Poignet<br>Coude'), card('Quels muscles sont fréquemment spastiques à l’épaule ?', 'Adducteurs<br>Rotateurs internes'), card('Quels groupes sont fréquemment spastiques distalement ?', 'Fléchisseurs du coude<br>Poignet<br>Doigts'), card('Quelle anomalie explique la spasticité centrale ?', 'Levée d’inhibition<br>du réflexe myotatique'), card('Quelle autre composante peut s’ajouter au syndrome pyramidal ?', 'Atteinte extrapyramidale<br>mouvements anormaux'),
  card('Quels troubles apparaissent avec le temps ?', 'Rétraction des spastiques<br>Affaiblissement antagoniste<br>Attitudes fixées'), card('Pourquoi l’évaluation doit-elle être répétée ?', 'Spasticité variable<br>dans le temps et les situations'), card('Pourquoi l’évaluation est-elle globale ?', 'Atteinte possible des<br>membres supérieur et inférieur'), card('Qui participe au bilan collectif ?', 'Équipe médicale<br>Paramédicaux<br>Patient et entourage'), card('Quels paramètres segmentaires analyser ?', 'Motricité<br>Spasticité<br>Rétraction'),
  card('Quel est l’objectif de la chirurgie fonctionnelle ?', 'Améliorer préhension<br>et positionnement spatial'), card('Quels sont les objectifs non fonctionnels ?', 'Hygiène<br>Nursing<br>Esthétique'), card('Quels facteurs excluent l’amélioration de préhension ?', 'Mauvais schéma proximal<br>Pas de fléchisseurs doigts<br>Pas de fléchisseur pouce'), card('Quand corriger précocement une attitude vicieuse ?', 'Si elle bloque la<br>récupération fonctionnelle'), card('Pourquoi regrouper les segments au même temps ?', 'Déformations et fonctions<br>segmentaires liées'),
  card('Prérequis d’une dénervation sélective ?', 'Muscle causal identifié<br>Pédicule individualisable'), card('Que ne corrige pas une dénervation ?', 'Une rétraction musculaire'), card('Pourquoi une dénervation peut-elle perdre son effet ?', 'Réinnervation de voisinage<br>Hypertrophie restante'), card('Effet des allongements tendineux ?', 'Corrigent rétraction<br>Réduisent spasticité'), card('Risque des allongements ?', 'Affaiblissement de la<br>commande volontaire'),
  card('Quand proposer une désinsertion proximale ?', 'Muscle rétracté<br>Fonction conservée'), card('Prérequis d’un transfert tendineux ?', 'Commande saine<br>Fonction substituable'), card('Quelle condition avant transfert ?', 'Réduire spasticité des<br>antagonistes'), card('Rôle d’une arthrodèse en main paralytique ?', 'Stabiliser<br>Simplifier la chaîne<br>Corriger une attitude'), card('Indication de suspension glénohumérale ?', 'Subluxation inférieure<br>douloureuse et réductible'),
  card('Contre-indication à la suspension par parties molles ?', 'Subluxation fixée'), card('Quand libérer l’épaule en adduction ?', 'Main fonctionnelle gênée<br>ou nursing axillaire impossible'), card('Quel test pour l’épaule en adduction ?', 'Bloc de l’anse<br>des pectoraux'), card('Ordre de libération antérieure d’épaule ?', 'Pectoralis major<br>Puis subscapularis'), card('Pourquoi respecter la capsule d’épaule ?', 'Prévenir instabilité<br>et raideur cicatricielle'),
  card('Quand discuter une arthrodèse glénohumérale ?', 'Luxation fixée douloureuse<br>ou bonne fonction distale'), card('Principale cause de flessum du coude ?', 'Biceps brachial'), card('Autres muscles du flessum du coude ?', 'Brachial antérieur<br>Brachioradialis<br>Épitrochléens'), card('Test de référence du flessum du coude ?', 'Bloc du nerf<br>musculocutané'), card('Que teste la variation avec la supination ?', 'Part du biceps brachial'),
  card('Indication de neurotomie musculocutanée ?', 'Spasticité importante<br>du biceps sans rétraction'), card('Quand privilégier un allongement de coude ?', 'Déformation dynamique<br>fonction conservée'), card('Particularité du flessum fixe sévère ?', 'Conserver parfois un flessum<br>résiduel pour le risque vasculaire'), card('Pourquoi la pronation fixée est-elle pénalisante ?', 'Empêche prises bimanuelles<br>et prises digitales'), card('Quand opérer une pronation ?', 'Pas de supination au-delà<br>de la position neutre'),
  card('Geste si supination résiduelle ?', 'Ténotomie pronator quadratus<br>± détente épitrochléens'), card('Geste si rond pronateur actif et attitude souple ?', 'Transfert supinateur<br>du rond pronateur'), card('Geste si pronation fixée et RP rétracté ?', 'Ténotomie du RP<br>± détente épitrochléens'), card('Attitude de poignet la plus fréquente ?', 'Capotage en flexion'), card('Avant un geste de poignet, quelles extensions tester ?', 'Poignet<br>Doigts longs'),
  card('Quel moteur peut réanimer l’extension du poignet ?', 'FCU sur ECRB<br>si commande saine'), card('Quand détendre les fléchisseurs du poignet ?', 'Extenseurs actifs<br>révélés au bloc'), card('Indication de résection première rangée ?', 'Poignet enraidi<br>muscles modérément spastiques'), card('Surveillance après résection première rangée ?', 'Contention rigide<br>Contrôles radiologiques'), card('Pourquoi stabiliser un poignet ?', 'Faciliter une prise rudimentaire<br>si synergie impossible'),
  card('Pourquoi ouvrir les doigts longs est difficile ?', 'Extenseurs rarement actifs'), card('Quels nerfs explorent les hyponeurotisations des fléchisseurs ?', 'Nerf médian<br>Nerf ulnaire distal'), card('Meilleurs candidats à hyponeurotisation ?', 'Peu rétractés<br>Améliorés par toxine<br>Antagonistes présents'), card('Principe du transfert FDS sur FDP ?', 'Allonger et synchroniser<br>les fléchisseurs'), card('Quel moteur peut réanimer l’EDC ?', 'FCU ou FCR<br>à commande saine'),
  card('Comment régler un transfert vers EDC ?', 'MCP étendues<br>poignet en rectitude'), card('Quel transfert ouvre la pince pouce–index ?', 'FCR ou PL sur EPL/ APL'), card('Déformation des intrinsèques spastiques ?', 'Flexion MCP<br>Extension IP'), card('Que démontre Bunnel positif ?', 'Rétraction intrinsèque'), card('Comment réaliser la manœuvre de Bunnel ?', 'Comparer flexion IPP<br>MCP étendues puis fléchies'),
  card('Effet d’une ténotomie distale des intrinsèques ?', 'Corrige rétraction<br>Réduit spasticité'), card('Effet d’une dénervation intrinsèque ?', 'Réduit spasticité<br>sans corriger rétraction'), card('Effet d’une désinsertion intrinsèque proximale ?', 'Agit sur spasticité<br>et rétraction'), card('Indication de neurotomie motrice ulnaire ?', 'Spasticité intrinsèque<br>sans rétraction'), card('Contre-indication de neurotomie ulnaire ?', 'Pince pollicidigitale<br>potentiellement fonctionnelle'),
  card('Quel outil sécurise une neurotomie ulnaire ?', 'Neurostimulateur'), card('Rôle du bloc médian au coude dans main fermée ?', 'Démasque intrinsèques<br>en détendant extrinsèques'), card('Rôle du bloc ulnaire au poignet ?', 'Mesure spasticité intrinsèque<br>et coût sur la pince'), card('Nom de la déformation du pouce dans la paume ?', 'Thumb in the palm'), card('Effet du FPL spastique ?', 'Flexion IP et MCP<br>enroulement palmaire'),
  card('Effet du FPB spastique ?', 'Flexion MCP<br>sans effet sur IP'), card('Effet adducteur et premier IOD ?', 'Fermeture première commissure'), card('Muscles déficitaires empêchant ouverture du pouce ?', 'EPL<br>APL<br>EPB'), card('Rôle de la rétraction cutanée de commissure ?', 'Aggrave progressivement<br>la fermeture'), card('Que teste le bloc ulnaire au poignet du pouce ?', 'Adducteur et FPB'),
  card('Que teste le bloc médian au poignet du pouce ?', 'Composante thénarienne'), card('Que teste le bloc médian au coude du pouce ?', 'Composante spastique<br>du FPL'), card('Risque d’un allongement FPL excessif ?', 'Hyperextension IP<br>peu fonctionnelle'), card('Quand stabiliser une MCP du pouce ?', 'Tendance à l’hyperextension'), card('Quand préférer arthrodèse trapézométacarpienne ?', 'Ouvrir la première commissure<br>sans MCP instable'),
  card('Comment obtenir une ouverture active du pouce ?', 'FCR, PL ou FPL<br>vers EPL ou M1'), card('Condition au transfert FPL–EPL ?', 'IP stabilisée<br>MCP mobile et stable'), card('Pourquoi immobiliser la commissure après geste du pouce ?', 'Maintenir l’ouverture<br>de première commissure'), card('Durée d’orthèse après arthrodèse TM ?', '6 semaines'), card('Pourquoi analyser le BR avant neurotomie MC ?', 'Il peut compenser<br>la flexion du coude'),
  card('Quand une chirurgie est-elle souvent discutée ?', 'À distance de phase initiale<br>après stabilisation neurologique'), card('Quand le geste devient adjuvant de rééducation ?', 'Attitude fixe précoce<br>bloquant récupération'), card('Pourquoi l’arthrodèse peut-elle être fonctionnelle ?', 'Stabilise un segment<br>pour utiliser moteurs restants'), card('Quelle erreur éviter après détente extrinsèque ?', 'Oublier la spasticité<br>intrinsèque démasquée'), card('Quelle erreur avant dénervation ?', 'Négliger une rétraction<br>ou une pince utile'),
  card('Quelle erreur avant transfert ?', 'Transférer un moteur<br>sans commande saine'), card('Quel objectif guide le choix de la chirurgie ?', 'Fonction attendue<br>et contrat patient'), card('Pourquoi les objectifs varient-ils selon l’étiologie ?', 'Potentiel de récupération<br>différent enfant/adulte'), card('Quelle attitude d’épaule gêne les soins ?', 'Adduction–rotation interne<br>fixée'), card('Quelle attitude de coude peut créer des troubles trophiques ?', 'Flessum avec plis<br>de flexion concernés'),
  card('Quel examen peut objectiver un moteur transférable ?', 'Examen clinique<br>Blocs, ITB, EMG'), card('Quelle position teste extension doigts dans l’algorithme ?', 'Poignet à 20° de flexion'), card('Que signifie une extension digitale absente ?', 'Rechercher spasticité/<br>rétraction par bloc'), card('Quel objectif de la chirurgie du pouce ?', 'Libérer l’ouverture<br>condition de préhension'), card('Quel geste en cas de rétraction cutanée de commissure ?', 'Plastie cutanée'),
  card('Que protège une immobilisation thoracobrachiale après épaule ?', 'Gain de libération<br>en abduction'), card('Pourquoi éviter excès d’allongement des fléchisseurs ?', 'Perte de commande active'), card('Quel signe motive objectifs hygiéniques ?', 'Main fermée ou attitude<br>empêchant soins'), card('Quels segments sont liés dans un programme ?', 'Épaule–coude<br>Coude–poignet<br>Poignet–main'), card('Quel résultat garantit le bloc anesthésique ?', 'Aucun : il éclaire<br>spasticité, rétraction et pronostic')
];

const item = (lettre, enonce, is_correct, justification) => ({ lettre, enonce, is_correct, justification });
const q = (enonce, correct, false1, false2, false3, false4, correction) => ({ enonce, correction_generale: correction, items: [item('A', correct, true, correction), item('B', false1, false, 'Cette proposition ne correspond pas aux indications ou au mécanisme décrit dans le chapitre.'), item('C', false2, false, 'Cette proposition ne correspond pas aux indications ou au mécanisme décrit dans le chapitre.'), item('D', false3, false, 'Cette proposition ne correspond pas aux indications ou au mécanisme décrit dans le chapitre.'), item('E', false4, false, 'Cette proposition ne correspond pas aux indications ou au mécanisme décrit dans le chapitre.')] });
const qcmSpecs = [
 ['Déficit et spasticité', [
 q('Dans l’hémiplégie centrale, quel déficit est particulièrement fréquent ?', 'Déficit des extenseurs des doigts, du poignet et du coude.', 'Déficit isolé des lombricaux sans atteinte proximale.', 'Paralysie systématique des rotateurs internes.', 'Atteinte exclusive des fléchisseurs des doigts.', 'Abolition du réflexe myotatique.', 'La source souligne la prédominance du déficit sur les extenseurs.'),
 q('Quel mécanisme participe à la spasticité centrale ?', 'Levée d’inhibition du réflexe myotatique.', 'Rupture d’un tendon fléchisseur.', 'Lésion d’un nerf périphérique isolé.', 'Diminution de la commande des antagonistes seule.', 'Immobilisation postopératoire.', 'La spasticité est liée à la levée d’inhibition du réflexe myotatique.'),
 q('Quel trouble secondaire peut fixer une déformation ?', 'Rétraction progressive des muscles spastiques.', 'Réinnervation immédiate du muscle antagoniste.', 'Guérison spontanée de la commande volontaire.', 'Augmentation systématique de la mobilité articulaire.', 'Disparition des déséquilibres musculaires.', 'Les rétractions et attitudes vicieuses se surajoutent au fil du temps.'),
 q('Quel profil favorise plus souvent une chirurgie fonctionnelle ?', 'Paralysie cérébrale de l’enfant avec muscles fonctionnels plus nombreux.', 'Cérébrolésion vasculaire récente avec récupération nulle.', 'Subluxation fixe isolée de l’épaule.', 'Flessum fixe du coude sans commande.', 'Main fermée sans fléchisseur utilisable.', 'Le potentiel de récupération et le nombre de muscles fonctionnels sont plus importants dans la paralysie cérébrale.'),
 q('Quel élément n’appartient pas à l’analyse segmentaire ?', 'La spasticité.', 'La motricité volontaire.', 'La rétraction.', 'La qualité du schéma moteur.', 'Le choix immédiat d’une technique standardisée.', 'La technique découle d’une analyse individualisée, non d’un protocole standard.')]],
 ['Bilan et objectifs', [
 q('Pourquoi répéter le bilan ?', 'La spasticité varie selon le temps et les situations.', 'Les rétractions disparaissent toujours en 24 heures.', 'La commande volontaire devient systématiquement normale.', 'Le bloc anesthésique remplace l’examen clinique.', 'Une seule consultation suffit à fixer tout programme.', 'La variabilité de la spasticité impose un bilan répété.'),
 q('Quel objectif est non fonctionnel ?', 'Faciliter l’hygiène et le nursing.', 'Restituer une pince fine normale.', 'Réparer une rupture tendineuse aiguë.', 'Augmenter la force de tous les muscles.', 'Créer une extension digitale active sans moteur.', 'Les objectifs hygiéniques et esthétiques sont non fonctionnels.'),
 q('Quel élément soutient un objectif de préhension ?', 'Présence de fléchisseurs mobilisables des doigts et du pouce.', 'Absence de tout schéma moteur proximal.', 'Main fermée sans commande volontaire.', 'Subluxation glénohumérale fixée.', 'Raideur complète de toutes les MCP.', 'La source conditionne l’ambition fonctionnelle à la commande proximale et aux fléchisseurs mobilisables.'),
 q('Quel rôle ont les blocs anesthésiques ?', 'Distinguer spasticité et rétraction.', 'Remplacer toute discussion avec le patient.', 'Corriger durablement une déformation fixe.', 'Créer un moteur à commander saine.', 'Supprimer définitivement une neurotomie.', 'Les blocs aident aussi à estimer le coût fonctionnel d’un geste.'),
 q('Pourquoi traiter plusieurs segments au même temps ?', 'Les fonctions épaule–coude, coude–poignet et poignet–main sont liées.', 'Chaque segment est totalement indépendant.', 'Cela évite toute évaluation préalable.', 'La chirurgie ne nécessite jamais de rééducation.', 'Les déformations se corrigent automatiquement.', 'Le regroupement tient à l’interdépendance segmentaire et au confort du patient.')]],
 ['Leviers chirurgicaux', [
 q('Quelle est une limite de la dénervation ?', 'Elle ne corrige pas une rétraction.', 'Elle allonge automatiquement tout tendon.', 'Elle garantit un effet définitif.', 'Elle améliore une articulation ankylosée.', 'Elle crée une commande volontaire saine.', 'La dénervation traite la spasticité, non la rétraction.'),
 q('Quel prérequis avant dénervation sélective ?', 'Identifier le muscle causal et son pédicule individualisable.', 'Absence totale de bilan clinique.', 'Existence d’une raideur fixée.', 'Transférer d’abord un antagoniste.', 'Ignorer la fonction résiduelle.', 'L’identification anatomique et fonctionnelle conditionne une dénervation sélective.'),
 q('Quel effet collatéral des allongements doit être anticipé ?', 'Affaiblissement de la commande active.', 'Création d’une extension active certaine.', 'Correction d’une denervation ancienne.', 'Suppression des besoins de contention.', 'Augmentation de la spasticité systématique.', 'Les allongements corrigent mais peuvent affaiblir.'),
 q('Quand une désinsertion proximale est-elle pertinente ?', 'Muscle rétracté ayant conservé une fonction.', 'Muscle sans aucun intérêt fonctionnel.', 'Subluxation glénohumérale non réductible.', 'Fracture aiguë du poignet.', 'Déficit sensitif pur.', 'Elle a peu d’intérêt si aucune fonction musculaire ne persiste.'),
 q('Quel est le rôle d’une arthrodèse ?', 'Stabiliser ou simplifier une chaîne polyarticulaire.', 'Réanimer directement un muscle paralysé.', 'Dénervé sélectivement des intrinsèques.', 'Traiter exclusivement une spasticité.', 'Remplacer tout transfert tendineux.', 'L’arthrodèse corrige une attitude et stabilise un segment.')]],
 ['Épaule et coude', [
 q('Quelle situation indique une suspension glénohumérale ?', 'Subluxation inférieure persistante, douloureuse et réductible.', 'Subluxation fixée indolore.', 'Toute adduction légère d’épaule.', 'Une paralysie sans douleur.', 'Une épaule stable et fonctionnelle.', 'L’indication repose sur la symptomatologie et la réductibilité.'),
 q('Quelle situation justifie une libération antérieure d’épaule ?', 'Attitude en adduction–rotation interne gênant une main fonctionnelle.', 'Subluxation fixe sans gêne.', 'Déficit isolé des extenseurs digitaux.', 'Pronation souple de l’avant-bras.', 'MCP en hyperextension isolée.', 'La libération vise la fonction ou le nursing axillaire.'),
 q('Quel est le premier muscle libéré à l’épaule ?', 'Pectoralis major.', 'Extensor carpi ulnaris.', 'Flexor pollicis longus.', 'Brachioradialis.', 'Pronator quadratus.', 'La libération est progressive, débutant par le pectoralis major.'),
 q('Quel test est très informatif devant flessum de coude ?', 'Bloc du nerf musculocutané.', 'Bloc du nerf radial au poignet.', 'Bloc du nerf ulnaire digital.', 'Test de Phalen.', 'Ponction glénohumérale.', 'Le bloc musculocutané précise spasticité, rétraction et rôle du BR.'),
 q('Quelle indication de neurotomie musculocutanée ?', 'Spasticité importante du biceps sans rétraction marquée.', 'Flessum fixe avec perte vasculaire.', 'Pronation souple avec RP actif.', 'Poignet en hyperextension.', 'Pince pouce-index fonctionnelle.', 'La neurotomie cible la spasticité du biceps, non une rétraction marquée.')]],
 ['Pronosupination et poignet', [
 q('Quand opérer une attitude en pronation ?', 'Absence de supination au-delà de la position neutre.', 'Dès qu’une supination active persiste.', 'Devant une extension digitale normale.', 'Devant une subluxation de l’épaule.', 'Devant un FPL spastique isolé.', 'L’absence de supination au-delà du neutre guide l’indication.'),
 q('Quel geste si pronation souple et rond pronateur actif ?', 'Transfert supinateur du rond pronateur.', 'Ténotomie du FCU.', 'Neurotomie ulnaire.', 'Arthrodèse trapézométacarpienne.', 'Désinsertion des thénariens.', 'Le transfert supinateur est proposé si le RP est actif et la déformation souple.'),
 q('Quelle attitude de poignet est la plus fréquente ?', 'Capotage en flexion.', 'Hyperextension fixe systématique.', 'Déviation radiale isolée.', 'Subluxation glénohumérale.', 'Luxation MCP du pouce.', 'Le capotage en flexion est le tableau le plus fréquent.'),
 q('Quel transfert peut réanimer l’extension du poignet ?', 'FCU sur ECRB si le FCU a une commande saine.', 'FPL sur FDP.', 'BR sur pectoralis major.', 'FDS sur pronator quadratus.', 'EPL sur biceps.', 'La qualité de commande du FCU est le prérequis du transfert.'),
 q('Quelle indication de résection de première rangée ?', 'Poignet enraidi avec fléchisseurs et extenseurs modérément spastiques et fonctionnels.', 'Poignet souple avec extenseurs absents.', 'Flessum du coude isolé.', 'Subluxation épaule réductible.', 'Pouce dans la paume isolé.', 'La résection raccourcit le carpe et vise un poignet enraidi bien sélectionné.')]],
 ['Doigts longs', [
 q('Pourquoi rechercher une extension digitale ?', 'Elle conditionne l’ouverture nécessaire à la préhension.', 'Elle n’influence jamais les objectifs.', 'Elle rend inutiles les fléchisseurs.', 'Elle interdit toute stabilisation de poignet.', 'Elle traduit une rétraction intrinsèque certaine.', 'L’ouverture digitale est un objectif central de la chirurgie fonctionnelle.'),
 q('Quel muscle peut réanimer l’EDC ?', 'FCU à commande saine.', 'Pectoralis major spastique.', 'Pronator quadratus seul.', 'Adducteur du pouce.', 'Biceps dénervé.', 'La source cite FCU ou FCR pour réanimer l’extension digitale.'),
 q('Quel principe du transfert FDS sur FDP ?', 'Synchroniser et allonger les fléchisseurs.', 'Dénervé les extenseurs.', 'Augmenter une hyperextension MCP.', 'Fixer l’épaule en rotation interne.', 'Traiter une luxation glénohumérale.', 'Le transfert des superficiels vers profonds participe à la détente des fléchisseurs.'),
 q('Quel profil est favorable à hyponeurotisation sélective ?', 'Muscle peu rétracté, amélioré par toxine et antagonistes présents.', 'Raideur MCP majeure.', 'Absence totale de tout antagoniste.', 'Pince pollicidigitale fonctionnelle dépendante des intrinsèques.', 'Subluxation épaule fixée.', 'Le bénéfice attendu est surtout sur la spasticité peu fixée.'),
 q('Quel problème peut apparaître après détente des extrinsèques ?', 'Spasticité intrinsèque démasquée.', 'Guérison d’une rétraction cutanée.', 'Création automatique d’une pince fine.', 'Disparition du besoin d’examen.', 'Stabilité immédiate de toutes les MCP.', 'Les intrinsèques doivent être réévalués après levée de l’enroulement extrinsèque.')]],
 ['Intrinsèques', [
 q('Quelle posture suggère une atteinte intrinsèque spastique ?', 'Flexion MCP et extension IP.', 'Extension MCP et flexion IP isolée.', 'Pronation isolée du coude.', 'Abduction complète de l’épaule.', 'Extension active normale du poignet.', 'La posture intrinsèque associe flexion MCP et extension IP.'),
 q('Que recherche la manœuvre de Bunnel ?', 'Rétraction des intrinsèques.', 'Rupture du long biceps.', 'Instabilité glénohumérale.', 'Syndrome canalaire médian.', 'Subluxation du carpe.', 'L’amélioration de flexion IPP quand les MCP fléchissent signe la rétraction intrinsèque.'),
 q('Quel geste agit sur spasticité sans agir sur rétraction ?', 'Dénervation intrinsèque.', 'Ténotomie distale.', 'Désinsertion proximale.', 'Plastie de commissure.', 'Arthrodèse TM.', 'La dénervation n’agit pas sur la composante rétractile.'),
 q('Quelle contre-indication à neurotomie ulnaire ?', 'Pince pollicidigitale potentiellement fonctionnelle.', 'Spasticité intrinsèque sans rétraction.', 'Main fermée avec besoin hygiénique.', 'Récidive crainte après geste tendineux.', 'Déficit des extenseurs du poignet.', 'La pince peut dépendre de l’adductor brevis et doit être préservée.'),
 q('Quel outil utilise-t-on pour identifier la branche motrice ulnaire ?', 'Neurostimulateur.', 'Goniomètre seul.', 'Radiographie de contrôle.', 'Tensiomètre.', 'Doppler veineux.', 'Le neurostimulateur guide l’identification et la vérification du geste.')]],
 ['Pouce dans la paume', [
 q('Quel muscle entraîne flexion IP et MCP du pouce ?', 'FPL spastique.', 'EPL déficitaire.', 'APL déficitaire.', 'Rond pronateur.', 'Brachioradialis.', 'Le FPL enroule le pouce dans la paume par flexion IP et MCP.'),
 q('Quel muscle ferme la première commissure sans agir sur IP/MCP ?', 'Adducteur du pouce.', 'FPL.', 'EPL.', 'Biceps brachial.', 'Extensor carpi radialis brevis.', 'Adducteur et premier IOD ferment la commissure.'),
 q('Quel bloc évalue la composante spastique du FPL ?', 'Bloc médian au coude.', 'Bloc ulnaire au poignet.', 'Bloc musculocutané.', 'Bloc de l’anse pectorale.', 'Bloc radial au coude.', 'Le médian au coude supprime la composante FPL.'),
 q('Quel risque d’un allongement FPL excessif ?', 'Hyperextension IP peu fonctionnelle.', 'Flessum irréductible du coude.', 'Pronation fixe.', 'Subluxation radiocarpienne.', 'Paralysie du pectoralis major.', 'L’allongement doit être protégé pour éviter l’hyperextension IP.'),
 q('Comment obtenir une ouverture active de commissure ?', 'Transfert FCR, PL ou FPL vers EPL ou premier métacarpien.', 'Neurotomie musculocutanée.', 'Suspension glénohumérale.', 'Ténotomie du pronator quadratus.', 'Arthrodèse glénohumérale.', 'Ces transferts mobilisent l’ouverture de la première commissure.')]]
];

const qcm = qcmSpecs.map(([theme, questions], index) => ({ label: `QCM — Série ${index + 1} · ${theme}`, kind: 'qcm', order_index: index + 1, questions }));
const dpDefinitions = [
 ['Hémiplégie et projet fonctionnel', 'Un homme de 58 ans présente une hémiplégie droite après accident vasculaire cérébral. Il souhaite stabiliser sa main pour participer aux gestes bimanuels. L’examen retrouve une commande proximale présente, une flexion des doigts et du pouce, un poignet capoté et une extension digitale incertaine. Le programme est discuté avec le patient, son entourage et l’équipe de rééducation ; un suivi fonctionnel est prévu.', ['Quel objectif est le plus cohérent ?', 'Améliorer une préhension rudimentaire.', 'Obtenir une main totalement normale.', 'Traiter une fracture récente.', 'Supprimer toute mobilité du membre.', 'Négliger les objectifs du patient.', 'La commande proximale et les fléchisseurs permettent d’envisager une ambition fonctionnelle.'], ['Le bloc des fléchisseurs améliore nettement l’extension des doigts. Quelle interprétation ?', 'Les fléchisseurs spastiques ou rétractés freinent l’extension.', 'Les extenseurs sont nécessairement normaux.', 'Une neurotomie ulnaire est indiquée.', 'Une arthrodèse d’épaule est requise.', 'Le pouce est obligatoirement stable.', 'Le bloc aide à séparer frein fléchisseur et déficit réel des extenseurs.'], ['Après détente des fléchisseurs, l’extension du poignet reste déficitaire mais le FCU a une commande saine. Quel geste peut être discuté ?', 'Transfert du FCU sur l’ECRB.', 'Ténotomie du pectoralis major.', 'Neurotomie musculocutanée.', 'Arthrodèse TM systématique.', 'Ténotomie du pronator quadratus seule.', 'Le FCU est un moteur de transfert si sa commande est saine.'], ['Au contrôle de rééducation, la prise demeure limitée mais plus stable. Quel message est exact ?', 'Une stabilisation peut améliorer une prise rudimentaire.', 'L’intervention est inutile sans pince fine.', 'La chirurgie fonctionnelle exclut toute arthrodèse.', 'Une prise rudimentaire ne compte pas.', 'Le suivi fonctionnel est inutile.', 'La source précise qu’une stabilisation peut faciliter des prises simples.'], ['Le patient demande pourquoi le bilan a été répété. Quelle réponse ?', 'La spasticité varie selon les situations.', 'La rétraction disparaît chaque jour.', 'Le bloc remplace toute clinique.', 'La chirurgie est standardisée.', 'L’EMG suffit seul.', 'Le caractère variable de la spasticité impose la répétition du bilan.']],
 ['Épaule douloureuse post-flaccide', 'Une femme de 46 ans, cérébrolésée après traumatisme, consulte pour douleur d’épaule et majoration de la spasticité. Une subluxation glénohumérale inférieure persiste après la phase flaccide. La réduction est possible et diminue la douleur. Les soins et le suivi de la douleur sont organisés.', ['Quelle indication opératoire est la plus cohérente ?', 'Suspension par parties molles.', 'Arthrodèse glénohumérale d’emblée.', 'Neurotomie ulnaire.', 'Transfert FDS–FDP.', 'Ténotomie du FPL.', 'Une subluxation douloureuse réductible correspond à l’indication décrite.'], ['La subluxation devient fixée au bilan. Quelle conséquence ?', 'La suspension par parties molles est contre-indiquée.', 'Le geste devient impératif.', 'Le FCU doit être transféré.', 'Le FPL doit être allongé.', 'Le bloc médian suffit.', 'La source oppose clairement la subluxation fixée à la suspension.'], ['Elle présente aussi une adduction–rotation interne qui empêche le nursing axillaire. Quelle évaluation est utile ?', 'Bloc de l’anse des pectoraux.', 'Bloc musculocutané.', 'Manœuvre de Bunnel.', 'Bloc ulnaire digital.', 'Test de supination seule.', 'Ce bloc aide à apprécier spasticité et rétraction des pectoraux.'], ['La rétraction est confirmée. Quelle libération est progressive ?', 'Pectoralis major puis subscapularis.', 'FPL puis EPL.', 'FCU puis ECRB.', 'Biceps puis brachioradialis.', 'Pronator quadratus puis RP.', 'Le pectoralis major est libéré avant le subscapularis.'], ['Au suivi, pourquoi surveiller la capsule lors de libération ?', 'Pour limiter instabilité et raideur cicatricielle.', 'Pour prévenir une pronation.', 'Pour traiter une spasticité ulnaire.', 'Pour remplacer une contention.', 'Pour augmenter le flessum.', 'Le respect capsulaire est une précaution explicitement rappelée.']],
 ['Flessum du coude', 'Un adolescent avec paralysie cérébrale a un flessum du coude gênant la toilette et le positionnement de la main. Les variations avec la supination sont nettes et la palpation suggère un rôle du brachioradialis. Un bloc musculocutané et un suivi avec rééducation sont programmés.', ['Quel muscle est le plus souvent impliqué ?', 'Biceps brachial.', 'EPL.', 'Adducteur du pouce.', 'Pronator quadratus.', 'FCR.', 'Le biceps est la première cause listée du flessum.'], ['Le bloc musculocutané corrige le flessum sans perte majeure de flexion utile. Quelle composante domine ?', 'Spasticité.', 'Raideur osseuse.', 'Instabilité MCP.', 'Déficit du FPL.', 'Subluxation glénohumérale.', 'La correction au bloc soutient une composante spastique.'], ['La spasticité bicipitale reste importante sans rétraction marquée. Quel geste est pertinent ?', 'Neurotomie musculocutanée.', 'Arthrodèse du poignet.', 'Ténotomie du PQ.', 'Transfert FCR–EPL.', 'Neurotomie ulnaire.', 'C’est l’indication de neurotomie donnée par la source.'], ['La déformation est au contraire dynamique avec flexion active conservée. Quelle stratégie ?', 'Allongement à la jonction tendinomusculaire.', 'Ténotomie d’emblée de tous les fléchisseurs.', 'Arthrodèse glénohumérale.', 'Neurotomie thénarienne.', 'Plastie de commissure.', 'Cette forme vise à conserver une fonction par un allongement adapté.'], ['Au suivi d’un flessum fixe très sévère, quelle précaution est juste ?', 'Accepter parfois un flessum résiduel pour le risque vasculaire.', 'Obtenir à tout prix l’extension complète.', 'Éviter toute protection du nerf radial.', 'Supprimer toute rééducation.', 'Dénervé systématiquement le BR.', 'La source recommande de ne pas exposer au risque vasculaire.']],
 ['Pronation fixée', 'Une jeune femme cérébrolésée ne peut utiliser sa main dans les prises bimanuelles : l’avant-bras reste en pronation. La supination n’atteint pas le neutre. Le rond pronateur est ensuite exploré ; une consultation de suivi mesure les possibilités de prise.', ['Quel retentissement explique la prise en charge ?', 'Empêche les prises bimanuelles.', 'Provoque une luxation glénohumérale obligatoire.', 'Rend toute flexion digitale normale.', 'Traite une spasticité du FPL.', 'Crée une hyperextension IP.', 'La pronation fixe limite notamment les prises bimanuelles.'], ['Quelle situation motive l’indication chirurgicale ?', 'Absence de supination au-delà du neutre.', 'Toute pronation minime.', 'Extension active des doigts.', 'MCP souples.', 'Bloc ulnaire positif.', 'Le seuil fonctionnel cité est l’absence de supination au-delà du neutre.'], ['Une supination résiduelle est retrouvée. Quel geste est possible ?', 'Ténotomie du pronator quadratus ± détente épitrochléens.', 'Transfert FPL–EPL.', 'Arthrodèse TM.', 'Neurotomie MC.', 'Ténotomie des interosseux.', 'La source réserve ce geste à la supination résiduelle.'], ['La déformation est souple et le rond pronateur est actif. Quel geste ?', 'Transfert supinateur du rond pronateur.', 'Ténotomie du FPL.', 'Dénervation ulnaire.', 'Ténodèse des radiaux.', 'Libération pectorale.', 'Un RP actif peut devenir moteur de supination.'], ['Au suivi, la supination s’améliore. Quel objectif fonctionnel évaluer ?', 'La reprise des prises bimanuelles.', 'La disparition d’une subluxation d’épaule.', 'La force du FPL seul.', 'Une immobilisation de l’épaule.', 'Une pince fine normale obligatoire.', 'Le bénéfice attendu est l’accès aux prises bimanueles et digitales.']],
 ['Capotage du poignet', 'Un homme de 62 ans après AVC a un poignet en flexion et une main qui se ferme lors des essais de prise. Les extenseurs sont difficiles à tester. Des blocs anesthésiques, l’analyse de l’EMG et un suivi de la prise palmodigitale sont prévus. Le patient est revu avec son ergothérapeute afin d’évaluer l’extension réellement disponible, l’hygiène palmaire et le bénéfice de chaque geste envisagé.', ['Quelle attitude est typique ?', 'Capotage du poignet en flexion.', 'Extension fixe systématique.', 'Supination bloquée isolée.', 'Luxation MCP du pouce.', 'Subluxation d’épaule.', 'Le capotage est l’attitude de poignet la plus fréquente.'], ['Pourquoi réaliser un bloc des fléchisseurs ?', 'Distinguer frein fléchisseur et déficit réel des extenseurs.', 'Préparer une arthrodèse glénohumérale.', 'Diagnostiquer une fracture.', 'Tester le pectoralis major.', 'Supprimer une rétraction cutanée.', 'Le bloc clarifie l’origine d’une extension déficitaire.'], ['Des extenseurs deviennent actifs après bloc. Quel geste conservateur discuter ?', 'Détente des fléchisseurs du poignet.', 'Neurotomie ulnaire systématique.', 'Arthrodèse TM.', 'Libération de l’épaule.', 'Ténotomie PQ obligatoire.', 'Des extenseurs actifs révélés au bloc autorisent une détente.'], ['Le FCU a une commande saine mais l’extension reste absente. Quel transfert ?', 'FCU vers ECRB.', 'FDS vers FDP.', 'FPL vers EPL obligatoirement.', 'BR vers biceps.', 'RP vers supinateur.', 'Le transfert FCU–ECRB vise l’extension du poignet.'], ['Au suivi, si la synergie reste irréalisable, quelle proposition est juste ?', 'Une stabilisation peut faciliter une prise rudimentaire.', 'La chirurgie devient sans objet.', 'La mobilité doit toujours être conservée.', 'Une arthrodèse est incompatible avec toute fonction.', 'Aucun contrôle fonctionnel n’est utile.', 'Les gestes non conservateurs peuvent conserver un bénéfice de préhension.']],
 ['Main fermée et doigts longs', 'Un homme de 36 ans traumatisé crânien présente une main fermée spastique, avec une flexion résiduelle des doigts. Après bloc médian au coude, l’ouverture progresse mais une composante intrinsèque apparaît. La rééducation et le suivi de l’ouverture digitale sont planifiés.', ['Quel est l’objectif prioritaire ?', 'Restaurer l’ouverture digitale utile à la prise.', 'Arthrodéser systématiquement l’épaule.', 'Dénervé tout le membre.', 'Supprimer toute flexion des doigts.', 'Traiter une pronation sans évaluation.', 'L’ouverture des doigts est centrale pour une préhension utile.'], ['Pourquoi le bloc médian au coude est-il utile ?', 'Il détend les extrinsèques et démasque les intrinsèques.', 'Il teste la capsule d’épaule.', 'Il remplace Bunnel.', 'Il répare une rétraction cutanée.', 'Il mesure une subluxation du carpe.', 'Le bloc met en évidence une composante intrinsèque masquée.'], ['Les fléchisseurs sont peu rétractés et la toxine a été efficace. Quel geste neurologique peut être discuté ?', 'Hyponeurotisation sélective.', 'Ténotomie pectorale.', 'Arthrodèse glénohumérale.', 'Transfert du RP.', 'Plastie de commissure.', 'Ce profil est favorable à une action sélective sur l’innervation.'], ['L’extension digitale reste déficitaire avec FCU bien commandé. Quel geste ?', 'Transfert FCU sur EDC.', 'Transfert FPL sur EPL uniquement.', 'Neurotomie MC.', 'Ténotomie du PQ.', 'Arthrodèse d’épaule.', 'FCU ou FCR peuvent réanimer l’EDC si leur commande est saine.'], ['Au contrôle, quelle complication décisionnelle faut-il éviter ?', 'Ignorer une spasticité intrinsèque démasquée.', 'Évaluer la préhension.', 'Poursuivre la rééducation.', 'Vérifier l’ouverture digitale.', 'Réévaluer le schéma moteur.', 'La détente extrinsèque peut révéler une composante intrinsèque nécessitant réévaluation.']],
 ['Intrinsèques et pince', 'Une patiente de 29 ans avec paralysie cérébrale a des MCP en flexion et des IP en extension. La flexion des IPP s’améliore lorsque les MCP sont fléchies. Une pince pollicidigitale rudimentaire reste possible. Les résultats et le suivi de la pince sont discutés.', ['Quel test est positif ?', 'Manœuvre de Bunnel pour rétraction intrinsèque.', 'Bloc musculocutané pour biceps.', 'Test d’épaule instable.', 'Test de pronation isolé.', 'Radiographie de première rangée.', 'L’amélioration selon la position MCP caractérise la rétraction intrinsèque.'], ['Quel effet doit être recherché avant geste ?', 'La part de spasticité et de rétraction.', 'Une fracture cachée obligatoire.', 'Une lésion du pectoralis.', 'Une subluxation d’épaule systématique.', 'Une rupture d’EPL.', 'Le choix entre ténotomie, dénervation et désinsertion dépend des composantes.'], ['La rétraction est limitée avec fonction conservée. Quel geste privilégier ?', 'Désinsertion proximale des interosseux.', 'Ténotomie de tous les fléchisseurs.', 'Arthrodèse TM.', 'Neurotomie MC.', 'Transfert RP.', 'La désinsertion agit sur les deux composantes en préservant une fonction sélectionnée.'], ['La pince dépend de l’adductor brevis. Quelle conduite ?', 'Éviter la neurotomie motrice ulnaire.', 'Dénervé systématiquement le rameau ulnaire.', 'Allonger le biceps.', 'Suspendre l’épaule.', 'Arthrodéser le coude.', 'La pince fonctionnelle est une contre-indication à la neurotomie ulnaire.'], ['Au suivi après désinsertion, MCP instables. Quelle mesure possible ?', 'Broche temporaire MCP en extension.', 'Immobilisation thoracobrachiale.', 'Bloc médian permanent.', 'Ténotomie du PQ.', 'Résection première rangée systématique.', 'La source prévoit une broche temporaire lorsque les MCP manquent de stabilité.']],
 ['Pouce dans la paume', 'Un garçon de 14 ans avec paralysie cérébrale a un pouce inclus dans la paume, rendant la pince pouce–index difficile. Il existe flexion IP et MCP, fermeture de commissure et peau rétractée. Des blocs médian et ulnaire sont réalisés ; l’ouverture de commissure sera suivie après traitement.', ['Quel muscle explique flexion IP et MCP ?', 'FPL spastique.', 'EPL déficitaire seul.', 'Biceps brachial.', 'Pronator quadratus.', 'FCU.', 'Le FPL provoque l’enroulement palmaire avec flexion IP et MCP.'], ['Le bloc ulnaire au poignet améliore l’ouverture. Quelle composante est testée ?', 'Adducteur et FPB.', 'Biceps et BR.', 'FPL isolé.', 'Pectoralis major.', 'Pronator teres.', 'Le bloc ulnaire au poignet explore la composante adducteur/FPB.'], ['Une rétraction cutanée persiste. Quel geste l’adresse ?', 'Plastie de première commissure.', 'Neurotomie musculocutanée.', 'Ténotomie du PQ.', 'Transfert FCU–ECRB.', 'Suspension glénohumérale.', 'La rétraction cutanée de commissure nécessite une plastie.'], ['L’allongement FPL est discuté. Quel risque prévenir ?', 'Hyperextension IP.', 'Flessum du coude.', 'Pronation fixe.', 'Luxation d’épaule.', 'Subluxation radiocarpienne.', 'L’excès d’allongement FPL expose à une IP peu fonctionnelle en hyperextension.'], ['Au suivi, l’ouverture active reste insuffisante malgré commissure souple. Quel geste peut la renforcer ?', 'Transfert FCR ou PL vers EPL/ APL.', 'Neurotomie MC.', 'Ténotomie du biceps.', 'Arthrodèse glénohumérale.', 'Transfert RP vers supinateur.', 'Les transferts vers EPL ou APL visent l’ouverture active.']]
];

const makeDpQuestion = (row, index) => {
  const [prompt, correct, a, b, c, d, correction] = row;
  return q(index ? `<em>Nouvel élément :</em> ${prompt}` : prompt, correct, a, b, c, d, correction);
};
const dp = dpDefinitions.map(([title, vignette, ...rows], index) => {
  const repeated = [...rows, rows[1], rows[2]].slice(0, 7); // same clinical chain, questions 6–7 revisit evolving decision explicitly below
  const extras = [
    ['Au rendez-vous de suivi, quel paramètre doit guider l’adaptation du programme ?', 'La fonction réellement gagnée dans l’objectif fixé.', 'Une technique imposée sans bilan.', 'La seule apparence radiologique.', 'La disparition de tout besoin de rééducation.', 'Le souhait du chirurgien seul.', 'Le contrat d’objectifs et le gain fonctionnel pilotent l’adaptation.'],
    ['Le patient rapporte une variation de l’attitude au cours de la journée. Quelle conduite ?', 'Répéter l’évaluation dans les situations pertinentes.', 'Conclure à une rétraction certaine.', 'Annuler le bilan clinique.', 'Dénervé sans test.', 'Ignorer le retentissement.', 'La variabilité de spasticité justifie une évaluation répétée.']
  ];
  const questions = [...rows, ...extras].slice(0, 7).map((row, questionIndex) => makeDpQuestion(row, questionIndex));
  return { label: `DP ${index + 1} · ${title}`, kind: 'dp', order_index: index + 9, vignette: `<strong>Contexte clinique</strong><br>${vignette}`, questions };
});

emitOrthopediePackage({ chapterDir, outputDir, fiche, facts, series: [...qcm, ...dp] });
